from ctypes import c_size_t
from typing import List, TYPE_CHECKING

from ..runtime import (
    cl_version,
    cl_version_khr,
    cl_name_version,
    cl_name_version_khr,
    cl_ulong,
    cl_external_memory_handle_type_khr,
    cl_semaphore_type_khr,
    cl_external_semaphore_handle_type_khr,
    cl_device_type,
    cl_device_mem_cache_type,
    cl_uint,
    cl_bool,
    cl_device_fp_config,
    cl_device_local_mem_type,
    cl_device_exec_capabilities,
    cl_command_queue_properties,
    cl_device_id,
    cl_device_partition_property,
    cl_device_affinity_domain,
    cl_device_svm_capabilities,
    cl_device_atomic_capabilities,
    cl_device_device_enqueue_capabilities,
    cl_device_command_buffer_capabilities_khr,
    cl_mutable_dispatch_fields_khr,
    cl_device_integer_dot_product_capabilities_khr,
    cl_device_integer_dot_product_acceleration_properties_khr,
    cl_device_pci_bus_info_khr,
    cl_device_terminate_capability_khr
)

from .clobject import CLObject
if TYPE_CHECKING:
    from .platform import Platform
    from .context import Context
    

class Device(CLObject):

    def create_context(self)->Context: ...

    @property
    def default_context(self)->Context: ...

    @property
    def unique_key(self)->str: ...

    @property
    def platform(self)->Platform: ...
    
    @property
    def id(self)->cl_device_id: ...

    @property
    def type(self)->cl_device_type: ...

    @property
    def vendor_id(self)->cl_uint: ...

    @property
    def max_compute_units(self)->cl_uint: ...

    @property
    def max_work_item_dimensions(self)->cl_uint: ...

    @property
    def max_work_item_sizes(self)->List[c_size_t]: ...

    @property
    def max_work_group_size(self)->c_size_t: ...

    @property
    def preferred_vector_width_char(self)->cl_uint: ...

    @property
    def preferred_vector_width_short(self)->cl_uint: ...

    @property
    def preferred_vector_width_int(self)->cl_uint: ...

    @property
    def preferred_vector_width_long(self)->cl_uint: ...

    @property
    def preferred_vector_width_float(self)->cl_uint: ...

    @property
    def preferred_vector_width_double(self)->cl_uint: ...

    @property
    def preferred_vector_width_half(self)->cl_uint: ...

    @property
    def preferred_vector_width_half(self)->cl_uint: ...

    @property
    def native_vector_width_char(self)->cl_uint: ...

    @property
    def native_vector_width_short(self)->cl_uint: ...

    @property
    def native_vector_width_int(self)->cl_uint: ...

    @property
    def native_vector_width_long(self)->cl_uint: ...

    @property
    def native_vector_width_float(self)->cl_uint: ...

    @property
    def native_vector_width_double(self)->cl_uint: ...

    @property
    def native_vector_width_half(self)->cl_uint: ...

    @property
    def max_clock_frequency(self)->cl_uint: ...

    @property
    def address_bits(self)->cl_uint: ...

    @property
    def max_mem_alloc_size(self)->cl_ulong: ...

    @property
    def image_support(self)->cl_bool: ...

    @property
    def max_read_image_args(self)->cl_uint: ...

    @property
    def max_write_image_args(self)->cl_uint: ...

    @property
    def max_read_write_image_args(self)->cl_uint: ...

    @property
    def il_version(self)->str: ...

    @property
    def il_version_khr(self)->str: ...

    @property
    def ils_with_version(self)->List[cl_name_version]: ...

    @property
    def ils_with_version_khr(self)->List[cl_name_version_khr]: ...

    @property
    def image2d_max_width(self)->c_size_t: ...

    @property
    def image2d_max_height(self)->c_size_t: ...

    @property
    def image3d_max_width(self)->c_size_t: ...

    @property
    def image3d_max_height(self)->c_size_t: ...

    @property
    def image3d_max_depth(self)->c_size_t: ...

    @property
    def image_max_buffer_size(self)->c_size_t: ...

    @property
    def image_max_array_size(self)->c_size_t: ...

    @property
    def max_samplers(self)->cl_uint: ...

    @property
    def image_pitch_alignment(self)->cl_uint: ...

    @property
    def image_pitch_alignment_khr(self)->cl_uint: ...

    @property
    def image_base_address_alignment(self)->cl_uint: ...

    @property
    def image_base_address_alignment_khr(self)->cl_uint: ...

    @property
    def max_pipe_args(self)->cl_uint: ...

    @property
    def pipe_max_active_reservations(self)->cl_uint: ...

    @property
    def pipe_max_packet_size(self)->cl_uint: ...

    @property
    def max_parameter_size(self)->c_size_t: ...

    @property
    def mem_base_addr_align(self)->cl_uint: ...

    @property
    def min_data_type_align_size(self)->cl_uint: ...

    @property
    def single_fp_config(self)->cl_device_fp_config: ...

    @property
    def double_fp_config(self)->cl_device_fp_config: ...

    @property
    def global_mem_cache_type(self)->cl_device_mem_cache_type: ...

    @property
    def global_mem_cacheline_size(self)->cl_uint: ...

    @property
    def global_mem_cache_size(self)->cl_ulong: ...

    @property
    def global_mem_size(self)->cl_ulong: ...

    @property
    def max_constant_buffer_size(self)->cl_ulong: ...

    @property
    def max_constant_args(self)->cl_uint: ...

    @property
    def max_global_variable_size(self)->c_size_t: ...

    @property
    def global_variable_preferred_total_size(self)->c_size_t: ...

    @property
    def local_mem_type(self)->cl_device_local_mem_type: ...

    @property
    def local_mem_size(self)->cl_ulong: ...

    @property
    def error_correction_support(self)->cl_bool: ...

    @property
    def host_unified_memory(self)->cl_bool: ...

    @property
    def profiling_timer_resolution(self)->c_size_t: ...

    @property
    def endian_little(self)->cl_bool: ...

    @property
    def available(self)->cl_bool: ...

    @property
    def compiler_available(self)->cl_bool: ...

    @property
    def linker_available(self)->cl_bool: ...

    @property
    def execution_capabilities(self)->cl_device_exec_capabilities: ...

    @property
    def queue_properties(self)->cl_command_queue_properties: ...

    @property
    def queue_on_host_properties(self)->cl_command_queue_properties: ...

    @property
    def queue_on_device_properties(self)->cl_command_queue_properties: ...

    @property
    def queue_on_device_preferred_size(self)->cl_uint: ...

    @property
    def queue_on_device_max_size(self)->cl_uint: ...

    @property
    def max_on_device_queues(self)->cl_uint: ...

    @property
    def max_on_device_events(self)->cl_uint: ...

    @property
    def built_in_kernels(self)->str: ...

    @property
    def built_in_kernels_with_version(self)->List[cl_name_version]: ...

    @property
    def built_in_kernels_with_version_khr(self)->List[cl_name_version_khr]: ...

    @property
    def platform(self)->Platform: ...

    @property
    def name(self)->str: ...

    @property
    def vendor(self)->str: ...

    @property
    def driver_version(self)->str: ...

    @property
    def profile(self)->str: ...

    @property
    def version(self)->str: ...

    @property
    def numeric_version(self)->cl_version: ...

    @property
    def numeric_version_khr(self)->cl_version_khr: ...

    @property
    def opencl_c_version(self)->str: ...

    @property
    def opencl_c_all_versions(self)->List[cl_name_version]: ...

    @property
    def opencl_c_numeric_version(self)->cl_version_khr: ...

    @property
    def opencl_c_features(self)->List[cl_name_version]: ...

    @property
    def extensions(self)->List[str]: ...

    @property
    def extensions_with_version(self)->List[cl_name_version]: ...

    @property
    def extensions_with_version_khr(self)->List[cl_name_version_khr]: ...

    @property
    def printf_buffer_size(self)->c_size_t: ...

    @property
    def preferred_interop_user_sync(self)->cl_bool: ...

    @property
    def parent_device(self)->cl_device_id: ...

    @property
    def partition_max_sub_devices(self)->cl_uint: ...

    @property
    def partition_properties(self)->List[cl_device_partition_property]: ...

    @property
    def partition_affinity_domain(self)->cl_device_affinity_domain: ...

    @property
    def partition_type(self)->List[cl_device_partition_property]: ...

    @property
    def reference_count(self)->cl_uint: ...

    @property
    def svm_capabilities(self)->cl_device_svm_capabilities: ...

    @property
    def preferred_platform_atomic_alignment(self)->cl_uint: ...

    @property
    def preferred_global_atomic_alignment(self)->cl_uint: ...

    @property
    def preferred_local_atomic_alignment(self)->cl_uint: ...

    @property
    def max_num_sub_groups(self)->cl_uint: ...

    @property
    def sub_group_independent_forward_progress(self)->cl_bool: ...

    @property
    def atomic_memory_capabilities(self)->cl_device_atomic_capabilities: ...

    @property
    def atomic_fence_capabilities(self)->cl_device_atomic_capabilities: ...

    @property
    def non_uniform_work_group_support(self)->cl_bool: ...

    @property
    def work_group_collective_functions_support(self)->cl_bool: ...

    @property
    def generic_address_space_support(self)->cl_bool: ...

    @property
    def device_enqueue_capabilities(self)->cl_device_device_enqueue_capabilities: ...

    @property
    def pipe_support(self)->cl_bool: ...

    @property
    def preferred_work_group_size_multiple(self)->c_size_t: ...

    @property
    def latest_conformance_version_passed(self)->str: ...

    @property
    def command_buffer_capabilities(self)->cl_device_command_buffer_capabilities_khr: ...

    @property
    def command_buffer_required_queue_properties(self)->cl_command_queue_properties: ...

    @property
    def command_buffer_num_sync_devices(self)->cl_uint: ...

    @property
    def command_buffer_sync_devices(self)->List[cl_device_id]: ...

    @property
    def mutable_dispatch_capabilities(self)->cl_mutable_dispatch_fields_khr: ...

    @property
    def uuid(self)->bytes: ...

    @property
    def driver_uuid(self)->bytes: ...

    @property
    def luid_valid(self)->cl_bool: ...

    @property
    def luid(self)->bytes: ...

    @property
    def node_mask(self)->cl_uint: ...

    @property
    def external_memory_import_handle_types(self)->List[cl_external_memory_handle_type_khr]: ...

    @property
    def external_memory_import_assume_linear_images_handle_types(self)->List[cl_external_memory_handle_type_khr]: ...

    @property
    def half_fp_config(self)->cl_device_fp_config: ...

    @property
    def integer_dot_product_capabilities(self)->cl_device_integer_dot_product_capabilities_khr: ...

    @property
    def integer_dot_product_acceleration_properties_8bit(self)->cl_device_integer_dot_product_acceleration_properties_khr: ...

    @property
    def integer_dot_product_acceleration_properties_4x8bit_packed(self)->cl_device_integer_dot_product_acceleration_properties_khr: ...

    @property
    def pci_bus_info(self)->cl_device_pci_bus_info_khr: ...

    @property
    def semaphore_types(self)->List[cl_semaphore_type_khr]: ...

    @property
    def semaphore_import_handle_types(self)->List[cl_external_semaphore_handle_type_khr]: ...

    @property
    def semaphore_export_handle_types(self)->List[cl_external_semaphore_handle_type_khr]: ...

    @property
    def spir_versions(self)->str: ...

    @property
    def max_named_barrier_count(self)->cl_uint: ...

    @property
    def terminate_capability(self)->cl_device_terminate_capability_khr: ...

    @property
    def cxx_for_opencl_numeric_version_ext(self)->cl_version: ...