from ctypes import c_char_p
from typing import Dict, List, Any, Set, Optional

from .device import Device
from .context import Context
from ..runtime import cl_build_status, cl_program_binary_type
from .build_options import BuildOptions
from .kernel_parser import KernelParser
from .kernel import Kernel


class Program:

    def __init__(self, context:Context, file_name:str="", includes:Optional[List[str]]=None, defines:Optional[Dict[str, Any]]=None, options:Optional[BuildOptions]=None, type_checked:bool=False, kernel_parser:KernelParser=None): ...

    @property
    def file_name(self)->str: ...
    
    @property
    def base_name(self)->str: ...
    
    @property
    def includes(self)->List[str]: ...
    
    @property
    def defines(self)->Dict[str, Any]: ...
    
    @property
    def options(self)->BuildOptions: ...
    
    @property
    def options_ptr(self)->c_char_p: ...
    
    @property
    def clean_code(self)->str: ...

    @property
    def line_map(self)->Dict[int, str]: ...
    
    @property
    def related_files(self)->Set[str]: ...
    
    @property
    def kernel_infos(self)->Dict[str, Dict[str, Any]]: ...

    @property
    def reference_count(self)->int: ...

    @property
    def context(self)->Context: ...

    @property
    def num_devices(self)->int: ...

    @property
    def devices(self)->List[Device]: ...

    @property
    def source(self)->str: ...

    @property
    def il(self)->str: ...

    @property
    def il_khr(self)->str: ...

    @property
    def binary_sizes(self)->Dict[Device, int]: ...

    @property
    def binaries(self)->Dict[Device, bytes]: ...

    @property
    def num_kernels(self)->int: ...

    @property
    def n_kernels(self)->int: ...

    @property
    def kernel_names(self)->List[str]: ...

    @property
    def scope_global_ctors_present(self)->bool: ...

    @property
    def scope_global_dtors_present(self)->bool: ...

    @property
    def build_status(self)->Dict[Device, cl_build_status]: ...

    @property
    def build_options(self)->Dict[Device, str]: ...
    
    @property
    def build_log(self)->Dict[Device, str]: ...
    
    @property
    def binary_type(self)->Dict[Device, cl_program_binary_type]: ...
    
    @property
    def global_variable_total_size(self)->Dict[Device, int]: ...

    def __getitem__(self, name:str)->Kernel: ...

    def __getattr__(self, name:str)->Kernel: ...