from ctypes import c_void_p, c_size_t, c_int64, c_char_p
from typing import Any

from .cltypes import (
    ErrorCode,
    cl_uint,
    cl_platform_id,
    cl_program,
    cl_device_id,
    cl_command_queue,
    cl_ulong,
    cl_event,
    cl_event_info,
    cl_command_execution_status,
    ptr_ptr_char,
    ptr_cl_kernel,
    cl_device_info,
    ptr_cl_platform_id,
    ptr_cl_uint,
    ptr_size_t,
    cl_platform_info,
    cl_device_type,
    ptr_cl_device_id,
    ptr_cl_int,
    ptr_int64,
    ptr_ptr_ubyte,
    ptr_cl_ulong,
    CL_CONTEXT_NOTIFY_CALLBACK,
    CL_BULD_PROGRAM_CALLBACK,
    CL_EVENT_NOTIFY_CALLBACK,
    cl_context,
    cl_context_info,
    cl_program_info,
    cl_program_build_info,
    cl_kernel,
    cl_kernel_info,
    cl_command_queue_info,
    cl_bitfield,
    cl_mem,
    cl_mem_flags,
    cl_mem_info,
    ptr_cl_event,
    ptr_cl_image_format,
    ptr_cl_image_desc,
    cl_addressing_mode,
    cl_filter_mode,
    cl_sampler,
    cl_sampler_info
)


class CL:

    class Func:

        def __call__(self, *args, **kwargs)->Any: ...

    @property
    def check_error(self)->bool: ...
    
    @check_error.setter
    def check_error(self, flag:bool)->None: ...

    @property
    def print_call(self)->bool: ...
    
    @print_call.setter
    def print_call(self, flag:bool)->None: ...

    @property
    def print_info(self)->bool: ...
    
    @print_info.setter
    def print_info(self, flag:bool)->None: ...

    def clGetPlatformIDs(num_entries: cl_uint, platforms: ptr_cl_platform_id, num_platforms: ptr_cl_uint)->ErrorCode: ...
    def clGetPlatformInfo(platform: cl_platform_id, param_name: cl_platform_info, param_value_size: c_size_t, param_value: c_void_p, param_value_size_ret: ptr_size_t)->ErrorCode: ...
    def clGetDeviceIDs(platform: cl_platform_id, device_type: cl_device_type, num_entries: cl_uint, devices: ptr_cl_device_id, num_devices: ptr_cl_uint)->ErrorCode: ...
    def clGetDeviceInfo(device:cl_device_id, param_name:cl_device_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode: ...
    def clCreateContext(properties:ptr_int64, num_devices:cl_uint, devices:ptr_cl_device_id, pfn_notify:CL_CONTEXT_NOTIFY_CALLBACK, user_data:c_void_p, errcode_ret:ptr_cl_int)->cl_context: ...
    def clReleaseContext(context:cl_context)->ErrorCode: ...
    def clGetContextInfo(context:cl_context, param_name:cl_context_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode:...
    def clCreateProgramWithSource(context:cl_context, count:cl_uint, strings:ptr_ptr_char, lengths:ptr_size_t, errcode_ret:ptr_cl_int)->cl_program:...
    def clCreateProgramWithBinary(context:cl_context, num_devices:cl_uint, device_list:ptr_cl_device_id, lengths:ptr_size_t, binaries:ptr_ptr_ubyte, binary_status:ptr_cl_int, errcode_ret:ptr_cl_int)->cl_program: ...
    def clBuildProgram(program:cl_program, num_devices:cl_uint, device_list:ptr_cl_device_id, options:c_char_p, pfn_notify:c_void_p, user_data:c_void_p)->ErrorCode:...
    def clGetProgramInfo(program:cl_program, param_name:cl_program_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode:...
    def clGetProgramBuildInfo(program:cl_program, device:cl_device_id, param_name:cl_program_build_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode:...
    def clReleaseProgram(program:cl_program)->ErrorCode:...
    def clCreateKernelsInProgram(program:cl_program, num_kernels:cl_uint, kernels:ptr_cl_kernel, num_kernels_ret:ptr_cl_uint)->ErrorCode:...
    def clGetKernelInfo(kernel:cl_kernel, param_name:cl_kernel_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode:...
    def clReleaseKernel(kernel:cl_kernel)->ErrorCode:...
    def clCreateCommandQueue(context:cl_context, device:cl_device_id, properties:cl_bitfield, errcode_ret:ptr_cl_int)->cl_command_queue: ...
    def clCreateCommandQueueWithProperties(context:cl_context, device:cl_device_id, properties:ptr_cl_ulong, errcode_ret:ptr_cl_int)->cl_command_queue: ...
    def clGetCommandQueueInfo(command_queue:cl_command_queue, param_name:cl_command_queue_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret: ptr_size_t)->ErrorCode: ...
    def clReleaseCommandQueue(command_queue:cl_command_queue)->ErrorCode: ...
    def clCreateBuffer(context:cl_context, flags:cl_mem_flags, size:c_size_t, host_ptr:c_void_p, errcode_ret:ptr_cl_int)->cl_mem: ...
    def clCreateBufferWithProperties(context:cl_context, properties:ptr_cl_ulong, flags:cl_mem_flags, size:c_size_t, host_ptr:c_void_p, errcode_ret:ptr_cl_int)->cl_mem: ...
    def clGetMemObjectInfo(memobj:cl_mem, param_name:cl_mem_info, param_value_size:c_size_t, param_value:c_void_p,param_value_size_ret:ptr_size_t)->ErrorCode: ...
    def clReleaseMemObject(memobj:cl_mem)->ErrorCode: ...
    def clEnqueueWriteBuffer(command_queue:cl_command_queue, buffer:cl_mem, blocking_write:bool, offset:c_size_t, size:c_size_t, ptr:c_void_p, num_events_in_wait_list:cl_uint, event_wait_list:ptr_cl_event, event:ptr_cl_event)->ErrorCode: ...
    def clEnqueueReadBuffer(command_queue:cl_command_queue, buffer:cl_mem, blocking_write:bool, offset:c_size_t, size:c_size_t, ptr:c_void_p, num_events_in_wait_list:cl_uint, event_wait_list:ptr_cl_event, event:ptr_cl_event)->ErrorCode: ...
    def clSetKernelArg(kernel:cl_kernel, arg_index:cl_uint, arg_size:c_size_t, arg_value:c_void_p)->ErrorCode: ...
    def clEnqueueNDRangeKernel(command_queue:cl_command_queue, kernel:cl_kernel, work_dim:cl_uint , global_work_offset:ptr_size_t, global_work_size:ptr_size_t, local_work_size:ptr_size_t, num_events_in_wait_list:cl_uint, event_wait_list:ptr_cl_event, event:ptr_cl_event)->ErrorCode: ...
    def clFinish(command_queue:cl_command_queue)->ErrorCode: ...
    def clGetEventInfo(event:cl_event, param_name:cl_event_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode: ...
    def clWaitForEvents(num_events:cl_uint, event_list:ptr_cl_event)->ErrorCode: ...
    def clCreateUserEvent(context:cl_context, errcode_ret:ptr_cl_int)->cl_event: ...
    def clSetUserEventStatus(event:cl_event, execution_status:cl_command_execution_status)->ErrorCode: ...
    def clSetEventCallback(event:cl_event, command_exec_callback_type:cl_command_execution_status, pfn_notify:CL_EVENT_NOTIFY_CALLBACK, user_data:c_void_p)->ErrorCode: ...
    def clReleaseEvent(event:cl_event)->ErrorCode: ...
    def clCreateImage(context:cl_context, flags:cl_mem_flags, image_format:ptr_cl_image_format, image_desc:ptr_cl_image_desc, host_ptr:c_void_p, errcode_ret:ptr_cl_int)->cl_mem: ...
    def clCreateImageWithProperties(context:cl_context, properties:ptr_cl_ulong, flags:cl_mem_flags, image_format:ptr_cl_image_format, image_desc:ptr_cl_image_desc, host_ptr:c_void_p, errcode_ret:ptr_cl_int)->cl_mem: ...
    def clEnqueueReadImage(command_queue:cl_command_queue, image:cl_mem, blocking_read:bool, origin:ptr_size_t, region:ptr_size_t, row_pitch:c_size_t, slice_pitch:c_size_t, ptr:c_void_p, num_events_in_wait_list:cl_uint, event_wait_list:ptr_cl_event, event:ptr_cl_event)->ErrorCode: ...
    def clEnqueueWriteImage(command_queue:cl_command_queue, image:cl_mem, blocking_write:bool, origin:ptr_size_t, region:ptr_size_t, input_row_pitch:c_size_t, input_slice_pitch:c_size_t, ptr:c_void_p, num_events_in_wait_list:cl_uint, event_wait_list:ptr_cl_event, event:ptr_cl_event)->ErrorCode: ...
    def clCreateSampler(context:cl_context, normalized_coords:bool, addressing_mode:cl_addressing_mode, filter_mode:cl_filter_mode, errcode_ret:ptr_cl_int)->cl_sampler: ...
    def clCreateSamplerWithProperties(context:cl_context, sampler_properties:ptr_cl_ulong, errcode_ret:ptr_cl_int)->cl_sampler: ...
    def clGetSamplerInfo(sampler:cl_sampler, param_name:cl_sampler_info, param_value_size:c_size_t, param_value:c_void_p, param_value_size_ret:ptr_size_t)->ErrorCode: ...
    def clReleaseSampler(sampler:cl_sampler)->ErrorCode: ...
    def clCreatePipe(context:cl_context, flags:cl_mem_flags, pipe_packet_size:cl_uint, pipe_max_packets:cl_uint, properties:ptr_int64, errcode_ret:ptr_cl_int)->cl_mem: ...

    @staticmethod
    def init(): ...
    