from typing import Union

from ..genVec2 import genVec2
from ..genVec3 import genVec3
from ..genVec4 import genVec4
from .int2 import int2
from .int3 import int3


class int4(genVec4):

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->int: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def w(self)->int: ...

    @w.setter
    def w(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->int2: ...

    @property
    def xy(self)->int2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xz(self)->int2: ...

    @xz.setter
    def xz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xw(self)->int2: ...

    @xw.setter
    def xw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->int2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->int2: ...

    @property
    def yz(self)->int2: ...

    @yz.setter
    def yz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yw(self)->int2: ...

    @yw.setter
    def yw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zx(self)->int2: ...

    @zx.setter
    def zx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zy(self)->int2: ...

    @zy.setter
    def zy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zz(self)->int2: ...

    @property
    def zw(self)->int2: ...

    @zw.setter
    def zw(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wx(self)->int2: ...

    @wx.setter
    def wx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wy(self)->int2: ...

    @wy.setter
    def wy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def wz(self)->int2: ...

    @wz.setter
    def wz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ww(self)->int2: ...

    @property
    def xxx(self)->int3: ...

    @property
    def xxy(self)->int3: ...

    @property
    def xxz(self)->int3: ...

    @property
    def xxw(self)->int3: ...

    @property
    def xyx(self)->int3: ...

    @property
    def xyy(self)->int3: ...

    @property
    def xyz(self)->int3: ...

    @xyz.setter
    def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xyw(self)->int3: ...

    @xyw.setter
    def xyw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzx(self)->int3: ...

    @property
    def xzy(self)->int3: ...

    @xzy.setter
    def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzz(self)->int3: ...

    @property
    def xzw(self)->int3: ...

    @xzw.setter
    def xzw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xwx(self)->int3: ...

    @property
    def xwy(self)->int3: ...

    @xwy.setter
    def xwy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xwz(self)->int3: ...

    @xwz.setter
    def xwz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xww(self)->int3: ...

    @property
    def yxx(self)->int3: ...

    @property
    def yxy(self)->int3: ...

    @property
    def yxz(self)->int3: ...

    @yxz.setter
    def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yxw(self)->int3: ...

    @yxw.setter
    def yxw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yyx(self)->int3: ...

    @property
    def yyy(self)->int3: ...

    @property
    def yyz(self)->int3: ...

    @property
    def yyw(self)->int3: ...

    @property
    def yzx(self)->int3: ...

    @yzx.setter
    def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yzy(self)->int3: ...

    @property
    def yzz(self)->int3: ...

    @property
    def yzw(self)->int3: ...

    @yzw.setter
    def yzw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ywx(self)->int3: ...

    @ywx.setter
    def ywx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ywy(self)->int3: ...

    @property
    def ywz(self)->int3: ...

    @ywz.setter
    def ywz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yww(self)->int3: ...

    @property
    def zxx(self)->int3: ...

    @property
    def zxy(self)->int3: ...

    @zxy.setter
    def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxz(self)->int3: ...

    @property
    def zxw(self)->int3: ...

    @zxw.setter
    def zxw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyx(self)->int3: ...

    @zyx.setter
    def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyy(self)->int3: ...

    @property
    def zyz(self)->int3: ...

    @property
    def zyw(self)->int3: ...

    @zyw.setter
    def zyw(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zzx(self)->int3: ...

    @property
    def zzy(self)->int3: ...

    @property
    def zzz(self)->int3: ...

    @property
    def zzw(self)->int3: ...

    @property
    def zwx(self)->int3: ...

    @zwx.setter
    def zwx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zwy(self)->int3: ...

    @zwy.setter
    def zwy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zwz(self)->int3: ...

    @property
    def zww(self)->int3: ...

    @property
    def wxx(self)->int3: ...

    @property
    def wxy(self)->int3: ...

    @wxy.setter
    def wxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wxz(self)->int3: ...

    @wxz.setter
    def wxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wxw(self)->int3: ...

    @property
    def wyx(self)->int3: ...

    @wyx.setter
    def wyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wyy(self)->int3: ...

    @property
    def wyz(self)->int3: ...

    @wyz.setter
    def wyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wyw(self)->int3: ...

    @property
    def wzx(self)->int3: ...

    @wzx.setter
    def wzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wzy(self)->int3: ...

    @wzy.setter
    def wzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def wzz(self)->int3: ...

    @property
    def wzw(self)->int3: ...

    @property
    def wwx(self)->int3: ...

    @property
    def wwy(self)->int3: ...

    @property
    def wwz(self)->int3: ...

    @property
    def www(self)->int3: ...

    @property
    def xxxx(self)->int4: ...

    @property
    def xxxy(self)->int4: ...

    @property
    def xxxz(self)->int4: ...

    @property
    def xxxw(self)->int4: ...

    @property
    def xxyx(self)->int4: ...

    @property
    def xxyy(self)->int4: ...

    @property
    def xxyz(self)->int4: ...

    @property
    def xxyw(self)->int4: ...

    @property
    def xxzx(self)->int4: ...

    @property
    def xxzy(self)->int4: ...

    @property
    def xxzz(self)->int4: ...

    @property
    def xxzw(self)->int4: ...

    @property
    def xxwx(self)->int4: ...

    @property
    def xxwy(self)->int4: ...

    @property
    def xxwz(self)->int4: ...

    @property
    def xxww(self)->int4: ...

    @property
    def xyxx(self)->int4: ...

    @property
    def xyxy(self)->int4: ...

    @property
    def xyxz(self)->int4: ...

    @property
    def xyxw(self)->int4: ...

    @property
    def xyyx(self)->int4: ...

    @property
    def xyyy(self)->int4: ...

    @property
    def xyyz(self)->int4: ...

    @property
    def xyyw(self)->int4: ...

    @property
    def xyzx(self)->int4: ...

    @property
    def xyzy(self)->int4: ...

    @property
    def xyzz(self)->int4: ...

    @property
    def xyzw(self)->int4: ...

    @xyzw.setter
    def xyzw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xywx(self)->int4: ...

    @property
    def xywy(self)->int4: ...

    @property
    def xywz(self)->int4: ...

    @xywz.setter
    def xywz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xyww(self)->int4: ...

    @property
    def xzxx(self)->int4: ...

    @property
    def xzxy(self)->int4: ...

    @property
    def xzxz(self)->int4: ...

    @property
    def xzxw(self)->int4: ...

    @property
    def xzyx(self)->int4: ...

    @property
    def xzyy(self)->int4: ...

    @property
    def xzyz(self)->int4: ...

    @property
    def xzyw(self)->int4: ...

    @xzyw.setter
    def xzyw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xzzx(self)->int4: ...

    @property
    def xzzy(self)->int4: ...

    @property
    def xzzz(self)->int4: ...

    @property
    def xzzw(self)->int4: ...

    @property
    def xzwx(self)->int4: ...

    @property
    def xzwy(self)->int4: ...

    @xzwy.setter
    def xzwy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xzwz(self)->int4: ...

    @property
    def xzww(self)->int4: ...

    @property
    def xwxx(self)->int4: ...

    @property
    def xwxy(self)->int4: ...

    @property
    def xwxz(self)->int4: ...

    @property
    def xwxw(self)->int4: ...

    @property
    def xwyx(self)->int4: ...

    @property
    def xwyy(self)->int4: ...

    @property
    def xwyz(self)->int4: ...

    @xwyz.setter
    def xwyz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xwyw(self)->int4: ...

    @property
    def xwzx(self)->int4: ...

    @property
    def xwzy(self)->int4: ...

    @xwzy.setter
    def xwzy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def xwzz(self)->int4: ...

    @property
    def xwzw(self)->int4: ...

    @property
    def xwwx(self)->int4: ...

    @property
    def xwwy(self)->int4: ...

    @property
    def xwwz(self)->int4: ...

    @property
    def xwww(self)->int4: ...

    @property
    def yxxx(self)->int4: ...

    @property
    def yxxy(self)->int4: ...

    @property
    def yxxz(self)->int4: ...

    @property
    def yxxw(self)->int4: ...

    @property
    def yxyx(self)->int4: ...

    @property
    def yxyy(self)->int4: ...

    @property
    def yxyz(self)->int4: ...

    @property
    def yxyw(self)->int4: ...

    @property
    def yxzx(self)->int4: ...

    @property
    def yxzy(self)->int4: ...

    @property
    def yxzz(self)->int4: ...

    @property
    def yxzw(self)->int4: ...

    @yxzw.setter
    def yxzw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yxwx(self)->int4: ...

    @property
    def yxwy(self)->int4: ...

    @property
    def yxwz(self)->int4: ...

    @yxwz.setter
    def yxwz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yxww(self)->int4: ...

    @property
    def yyxx(self)->int4: ...

    @property
    def yyxy(self)->int4: ...

    @property
    def yyxz(self)->int4: ...

    @property
    def yyxw(self)->int4: ...

    @property
    def yyyx(self)->int4: ...

    @property
    def yyyy(self)->int4: ...

    @property
    def yyyz(self)->int4: ...

    @property
    def yyyw(self)->int4: ...

    @property
    def yyzx(self)->int4: ...

    @property
    def yyzy(self)->int4: ...

    @property
    def yyzz(self)->int4: ...

    @property
    def yyzw(self)->int4: ...

    @property
    def yywx(self)->int4: ...

    @property
    def yywy(self)->int4: ...

    @property
    def yywz(self)->int4: ...

    @property
    def yyww(self)->int4: ...

    @property
    def yzxx(self)->int4: ...

    @property
    def yzxy(self)->int4: ...

    @property
    def yzxz(self)->int4: ...

    @property
    def yzxw(self)->int4: ...

    @yzxw.setter
    def yzxw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yzyx(self)->int4: ...

    @property
    def yzyy(self)->int4: ...

    @property
    def yzyz(self)->int4: ...

    @property
    def yzyw(self)->int4: ...

    @property
    def yzzx(self)->int4: ...

    @property
    def yzzy(self)->int4: ...

    @property
    def yzzz(self)->int4: ...

    @property
    def yzzw(self)->int4: ...

    @property
    def yzwx(self)->int4: ...

    @yzwx.setter
    def yzwx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def yzwy(self)->int4: ...

    @property
    def yzwz(self)->int4: ...

    @property
    def yzww(self)->int4: ...

    @property
    def ywxx(self)->int4: ...

    @property
    def ywxy(self)->int4: ...

    @property
    def ywxz(self)->int4: ...

    @ywxz.setter
    def ywxz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ywxw(self)->int4: ...

    @property
    def ywyx(self)->int4: ...

    @property
    def ywyy(self)->int4: ...

    @property
    def ywyz(self)->int4: ...

    @property
    def ywyw(self)->int4: ...

    @property
    def ywzx(self)->int4: ...

    @ywzx.setter
    def ywzx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def ywzy(self)->int4: ...

    @property
    def ywzz(self)->int4: ...

    @property
    def ywzw(self)->int4: ...

    @property
    def ywwx(self)->int4: ...

    @property
    def ywwy(self)->int4: ...

    @property
    def ywwz(self)->int4: ...

    @property
    def ywww(self)->int4: ...

    @property
    def zxxx(self)->int4: ...

    @property
    def zxxy(self)->int4: ...

    @property
    def zxxz(self)->int4: ...

    @property
    def zxxw(self)->int4: ...

    @property
    def zxyx(self)->int4: ...

    @property
    def zxyy(self)->int4: ...

    @property
    def zxyz(self)->int4: ...

    @property
    def zxyw(self)->int4: ...

    @zxyw.setter
    def zxyw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zxzx(self)->int4: ...

    @property
    def zxzy(self)->int4: ...

    @property
    def zxzz(self)->int4: ...

    @property
    def zxzw(self)->int4: ...

    @property
    def zxwx(self)->int4: ...

    @property
    def zxwy(self)->int4: ...

    @zxwy.setter
    def zxwy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zxwz(self)->int4: ...

    @property
    def zxww(self)->int4: ...

    @property
    def zyxx(self)->int4: ...

    @property
    def zyxy(self)->int4: ...

    @property
    def zyxz(self)->int4: ...

    @property
    def zyxw(self)->int4: ...

    @zyxw.setter
    def zyxw(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zyyx(self)->int4: ...

    @property
    def zyyy(self)->int4: ...

    @property
    def zyyz(self)->int4: ...

    @property
    def zyyw(self)->int4: ...

    @property
    def zyzx(self)->int4: ...

    @property
    def zyzy(self)->int4: ...

    @property
    def zyzz(self)->int4: ...

    @property
    def zyzw(self)->int4: ...

    @property
    def zywx(self)->int4: ...

    @zywx.setter
    def zywx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zywy(self)->int4: ...

    @property
    def zywz(self)->int4: ...

    @property
    def zyww(self)->int4: ...

    @property
    def zzxx(self)->int4: ...

    @property
    def zzxy(self)->int4: ...

    @property
    def zzxz(self)->int4: ...

    @property
    def zzxw(self)->int4: ...

    @property
    def zzyx(self)->int4: ...

    @property
    def zzyy(self)->int4: ...

    @property
    def zzyz(self)->int4: ...

    @property
    def zzyw(self)->int4: ...

    @property
    def zzzx(self)->int4: ...

    @property
    def zzzy(self)->int4: ...

    @property
    def zzzz(self)->int4: ...

    @property
    def zzzw(self)->int4: ...

    @property
    def zzwx(self)->int4: ...

    @property
    def zzwy(self)->int4: ...

    @property
    def zzwz(self)->int4: ...

    @property
    def zzww(self)->int4: ...

    @property
    def zwxx(self)->int4: ...

    @property
    def zwxy(self)->int4: ...

    @zwxy.setter
    def zwxy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zwxz(self)->int4: ...

    @property
    def zwxw(self)->int4: ...

    @property
    def zwyx(self)->int4: ...

    @zwyx.setter
    def zwyx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def zwyy(self)->int4: ...

    @property
    def zwyz(self)->int4: ...

    @property
    def zwyw(self)->int4: ...

    @property
    def zwzx(self)->int4: ...

    @property
    def zwzy(self)->int4: ...

    @property
    def zwzz(self)->int4: ...

    @property
    def zwzw(self)->int4: ...

    @property
    def zwwx(self)->int4: ...

    @property
    def zwwy(self)->int4: ...

    @property
    def zwwz(self)->int4: ...

    @property
    def zwww(self)->int4: ...

    @property
    def wxxx(self)->int4: ...

    @property
    def wxxy(self)->int4: ...

    @property
    def wxxz(self)->int4: ...

    @property
    def wxxw(self)->int4: ...

    @property
    def wxyx(self)->int4: ...

    @property
    def wxyy(self)->int4: ...

    @property
    def wxyz(self)->int4: ...

    @wxyz.setter
    def wxyz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wxyw(self)->int4: ...

    @property
    def wxzx(self)->int4: ...

    @property
    def wxzy(self)->int4: ...

    @wxzy.setter
    def wxzy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wxzz(self)->int4: ...

    @property
    def wxzw(self)->int4: ...

    @property
    def wxwx(self)->int4: ...

    @property
    def wxwy(self)->int4: ...

    @property
    def wxwz(self)->int4: ...

    @property
    def wxww(self)->int4: ...

    @property
    def wyxx(self)->int4: ...

    @property
    def wyxy(self)->int4: ...

    @property
    def wyxz(self)->int4: ...

    @wyxz.setter
    def wyxz(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wyxw(self)->int4: ...

    @property
    def wyyx(self)->int4: ...

    @property
    def wyyy(self)->int4: ...

    @property
    def wyyz(self)->int4: ...

    @property
    def wyyw(self)->int4: ...

    @property
    def wyzx(self)->int4: ...

    @wyzx.setter
    def wyzx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wyzy(self)->int4: ...

    @property
    def wyzz(self)->int4: ...

    @property
    def wyzw(self)->int4: ...

    @property
    def wywx(self)->int4: ...

    @property
    def wywy(self)->int4: ...

    @property
    def wywz(self)->int4: ...

    @property
    def wyww(self)->int4: ...

    @property
    def wzxx(self)->int4: ...

    @property
    def wzxy(self)->int4: ...

    @wzxy.setter
    def wzxy(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wzxz(self)->int4: ...

    @property
    def wzxw(self)->int4: ...

    @property
    def wzyx(self)->int4: ...

    @wzyx.setter
    def wzyx(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def wzyy(self)->int4: ...

    @property
    def wzyz(self)->int4: ...

    @property
    def wzyw(self)->int4: ...

    @property
    def wzzx(self)->int4: ...

    @property
    def wzzy(self)->int4: ...

    @property
    def wzzz(self)->int4: ...

    @property
    def wzzw(self)->int4: ...

    @property
    def wzwx(self)->int4: ...

    @property
    def wzwy(self)->int4: ...

    @property
    def wzwz(self)->int4: ...

    @property
    def wzww(self)->int4: ...

    @property
    def wwxx(self)->int4: ...

    @property
    def wwxy(self)->int4: ...

    @property
    def wwxz(self)->int4: ...

    @property
    def wwxw(self)->int4: ...

    @property
    def wwyx(self)->int4: ...

    @property
    def wwyy(self)->int4: ...

    @property
    def wwyz(self)->int4: ...

    @property
    def wwyw(self)->int4: ...

    @property
    def wwzx(self)->int4: ...

    @property
    def wwzy(self)->int4: ...

    @property
    def wwzz(self)->int4: ...

    @property
    def wwzw(self)->int4: ...

    @property
    def wwwx(self)->int4: ...

    @property
    def wwwy(self)->int4: ...

    @property
    def wwwz(self)->int4: ...

    @property
    def wwww(self)->int4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def b(self)->int: ...

    @b.setter
    def b(self, value:Union[bool, int, float])->None: ...

    @property
    def a(self)->int: ...

    @a.setter
    def a(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->int2: ...

    @property
    def rg(self)->int2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rb(self)->int2: ...

    @rb.setter
    def rb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ra(self)->int2: ...

    @ra.setter
    def ra(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->int2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->int2: ...

    @property
    def gb(self)->int2: ...

    @gb.setter
    def gb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ga(self)->int2: ...

    @ga.setter
    def ga(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def br(self)->int2: ...

    @br.setter
    def br(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bg(self)->int2: ...

    @bg.setter
    def bg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bb(self)->int2: ...

    @property
    def ba(self)->int2: ...

    @ba.setter
    def ba(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ar(self)->int2: ...

    @ar.setter
    def ar(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ag(self)->int2: ...

    @ag.setter
    def ag(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def ab(self)->int2: ...

    @ab.setter
    def ab(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def aa(self)->int2: ...

    @property
    def rrr(self)->int3: ...

    @property
    def rrg(self)->int3: ...

    @property
    def rrb(self)->int3: ...

    @property
    def rra(self)->int3: ...

    @property
    def rgr(self)->int3: ...

    @property
    def rgg(self)->int3: ...

    @property
    def rgb(self)->int3: ...

    @rgb.setter
    def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rga(self)->int3: ...

    @rga.setter
    def rga(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbr(self)->int3: ...

    @property
    def rbg(self)->int3: ...

    @rbg.setter
    def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbb(self)->int3: ...

    @property
    def rba(self)->int3: ...

    @rba.setter
    def rba(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rar(self)->int3: ...

    @property
    def rag(self)->int3: ...

    @rag.setter
    def rag(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rab(self)->int3: ...

    @rab.setter
    def rab(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def raa(self)->int3: ...

    @property
    def grr(self)->int3: ...

    @property
    def grg(self)->int3: ...

    @property
    def grb(self)->int3: ...

    @grb.setter
    def grb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gra(self)->int3: ...

    @gra.setter
    def gra(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggr(self)->int3: ...

    @property
    def ggg(self)->int3: ...

    @property
    def ggb(self)->int3: ...

    @property
    def gga(self)->int3: ...

    @property
    def gbr(self)->int3: ...

    @gbr.setter
    def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gbg(self)->int3: ...

    @property
    def gbb(self)->int3: ...

    @property
    def gba(self)->int3: ...

    @gba.setter
    def gba(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gar(self)->int3: ...

    @gar.setter
    def gar(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gag(self)->int3: ...

    @property
    def gab(self)->int3: ...

    @gab.setter
    def gab(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gaa(self)->int3: ...

    @property
    def brr(self)->int3: ...

    @property
    def brg(self)->int3: ...

    @brg.setter
    def brg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def brb(self)->int3: ...

    @property
    def bra(self)->int3: ...

    @bra.setter
    def bra(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgr(self)->int3: ...

    @bgr.setter
    def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgg(self)->int3: ...

    @property
    def bgb(self)->int3: ...

    @property
    def bga(self)->int3: ...

    @bga.setter
    def bga(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bbr(self)->int3: ...

    @property
    def bbg(self)->int3: ...

    @property
    def bbb(self)->int3: ...

    @property
    def bba(self)->int3: ...

    @property
    def bar(self)->int3: ...

    @bar.setter
    def bar(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bag(self)->int3: ...

    @bag.setter
    def bag(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bab(self)->int3: ...

    @property
    def baa(self)->int3: ...

    @property
    def arr(self)->int3: ...

    @property
    def arg(self)->int3: ...

    @arg.setter
    def arg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def arb(self)->int3: ...

    @arb.setter
    def arb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ara(self)->int3: ...

    @property
    def agr(self)->int3: ...

    @agr.setter
    def agr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def agg(self)->int3: ...

    @property
    def agb(self)->int3: ...

    @agb.setter
    def agb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def aga(self)->int3: ...

    @property
    def abr(self)->int3: ...

    @abr.setter
    def abr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def abg(self)->int3: ...

    @abg.setter
    def abg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def abb(self)->int3: ...

    @property
    def aba(self)->int3: ...

    @property
    def aar(self)->int3: ...

    @property
    def aag(self)->int3: ...

    @property
    def aab(self)->int3: ...

    @property
    def aaa(self)->int3: ...

    @property
    def rrrr(self)->int4: ...

    @property
    def rrrg(self)->int4: ...

    @property
    def rrrb(self)->int4: ...

    @property
    def rrra(self)->int4: ...

    @property
    def rrgr(self)->int4: ...

    @property
    def rrgg(self)->int4: ...

    @property
    def rrgb(self)->int4: ...

    @property
    def rrga(self)->int4: ...

    @property
    def rrbr(self)->int4: ...

    @property
    def rrbg(self)->int4: ...

    @property
    def rrbb(self)->int4: ...

    @property
    def rrba(self)->int4: ...

    @property
    def rrar(self)->int4: ...

    @property
    def rrag(self)->int4: ...

    @property
    def rrab(self)->int4: ...

    @property
    def rraa(self)->int4: ...

    @property
    def rgrr(self)->int4: ...

    @property
    def rgrg(self)->int4: ...

    @property
    def rgrb(self)->int4: ...

    @property
    def rgra(self)->int4: ...

    @property
    def rggr(self)->int4: ...

    @property
    def rggg(self)->int4: ...

    @property
    def rggb(self)->int4: ...

    @property
    def rgga(self)->int4: ...

    @property
    def rgbr(self)->int4: ...

    @property
    def rgbg(self)->int4: ...

    @property
    def rgbb(self)->int4: ...

    @property
    def rgba(self)->int4: ...

    @rgba.setter
    def rgba(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rgar(self)->int4: ...

    @property
    def rgag(self)->int4: ...

    @property
    def rgab(self)->int4: ...

    @rgab.setter
    def rgab(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rgaa(self)->int4: ...

    @property
    def rbrr(self)->int4: ...

    @property
    def rbrg(self)->int4: ...

    @property
    def rbrb(self)->int4: ...

    @property
    def rbra(self)->int4: ...

    @property
    def rbgr(self)->int4: ...

    @property
    def rbgg(self)->int4: ...

    @property
    def rbgb(self)->int4: ...

    @property
    def rbga(self)->int4: ...

    @rbga.setter
    def rbga(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rbbr(self)->int4: ...

    @property
    def rbbg(self)->int4: ...

    @property
    def rbbb(self)->int4: ...

    @property
    def rbba(self)->int4: ...

    @property
    def rbar(self)->int4: ...

    @property
    def rbag(self)->int4: ...

    @rbag.setter
    def rbag(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rbab(self)->int4: ...

    @property
    def rbaa(self)->int4: ...

    @property
    def rarr(self)->int4: ...

    @property
    def rarg(self)->int4: ...

    @property
    def rarb(self)->int4: ...

    @property
    def rara(self)->int4: ...

    @property
    def ragr(self)->int4: ...

    @property
    def ragg(self)->int4: ...

    @property
    def ragb(self)->int4: ...

    @ragb.setter
    def ragb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def raga(self)->int4: ...

    @property
    def rabr(self)->int4: ...

    @property
    def rabg(self)->int4: ...

    @rabg.setter
    def rabg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def rabb(self)->int4: ...

    @property
    def raba(self)->int4: ...

    @property
    def raar(self)->int4: ...

    @property
    def raag(self)->int4: ...

    @property
    def raab(self)->int4: ...

    @property
    def raaa(self)->int4: ...

    @property
    def grrr(self)->int4: ...

    @property
    def grrg(self)->int4: ...

    @property
    def grrb(self)->int4: ...

    @property
    def grra(self)->int4: ...

    @property
    def grgr(self)->int4: ...

    @property
    def grgg(self)->int4: ...

    @property
    def grgb(self)->int4: ...

    @property
    def grga(self)->int4: ...

    @property
    def grbr(self)->int4: ...

    @property
    def grbg(self)->int4: ...

    @property
    def grbb(self)->int4: ...

    @property
    def grba(self)->int4: ...

    @grba.setter
    def grba(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def grar(self)->int4: ...

    @property
    def grag(self)->int4: ...

    @property
    def grab(self)->int4: ...

    @grab.setter
    def grab(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def graa(self)->int4: ...

    @property
    def ggrr(self)->int4: ...

    @property
    def ggrg(self)->int4: ...

    @property
    def ggrb(self)->int4: ...

    @property
    def ggra(self)->int4: ...

    @property
    def gggr(self)->int4: ...

    @property
    def gggg(self)->int4: ...

    @property
    def gggb(self)->int4: ...

    @property
    def ggga(self)->int4: ...

    @property
    def ggbr(self)->int4: ...

    @property
    def ggbg(self)->int4: ...

    @property
    def ggbb(self)->int4: ...

    @property
    def ggba(self)->int4: ...

    @property
    def ggar(self)->int4: ...

    @property
    def ggag(self)->int4: ...

    @property
    def ggab(self)->int4: ...

    @property
    def ggaa(self)->int4: ...

    @property
    def gbrr(self)->int4: ...

    @property
    def gbrg(self)->int4: ...

    @property
    def gbrb(self)->int4: ...

    @property
    def gbra(self)->int4: ...

    @gbra.setter
    def gbra(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gbgr(self)->int4: ...

    @property
    def gbgg(self)->int4: ...

    @property
    def gbgb(self)->int4: ...

    @property
    def gbga(self)->int4: ...

    @property
    def gbbr(self)->int4: ...

    @property
    def gbbg(self)->int4: ...

    @property
    def gbbb(self)->int4: ...

    @property
    def gbba(self)->int4: ...

    @property
    def gbar(self)->int4: ...

    @gbar.setter
    def gbar(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gbag(self)->int4: ...

    @property
    def gbab(self)->int4: ...

    @property
    def gbaa(self)->int4: ...

    @property
    def garr(self)->int4: ...

    @property
    def garg(self)->int4: ...

    @property
    def garb(self)->int4: ...

    @garb.setter
    def garb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gara(self)->int4: ...

    @property
    def gagr(self)->int4: ...

    @property
    def gagg(self)->int4: ...

    @property
    def gagb(self)->int4: ...

    @property
    def gaga(self)->int4: ...

    @property
    def gabr(self)->int4: ...

    @gabr.setter
    def gabr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def gabg(self)->int4: ...

    @property
    def gabb(self)->int4: ...

    @property
    def gaba(self)->int4: ...

    @property
    def gaar(self)->int4: ...

    @property
    def gaag(self)->int4: ...

    @property
    def gaab(self)->int4: ...

    @property
    def gaaa(self)->int4: ...

    @property
    def brrr(self)->int4: ...

    @property
    def brrg(self)->int4: ...

    @property
    def brrb(self)->int4: ...

    @property
    def brra(self)->int4: ...

    @property
    def brgr(self)->int4: ...

    @property
    def brgg(self)->int4: ...

    @property
    def brgb(self)->int4: ...

    @property
    def brga(self)->int4: ...

    @brga.setter
    def brga(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def brbr(self)->int4: ...

    @property
    def brbg(self)->int4: ...

    @property
    def brbb(self)->int4: ...

    @property
    def brba(self)->int4: ...

    @property
    def brar(self)->int4: ...

    @property
    def brag(self)->int4: ...

    @brag.setter
    def brag(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def brab(self)->int4: ...

    @property
    def braa(self)->int4: ...

    @property
    def bgrr(self)->int4: ...

    @property
    def bgrg(self)->int4: ...

    @property
    def bgrb(self)->int4: ...

    @property
    def bgra(self)->int4: ...

    @bgra.setter
    def bgra(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bggr(self)->int4: ...

    @property
    def bggg(self)->int4: ...

    @property
    def bggb(self)->int4: ...

    @property
    def bgga(self)->int4: ...

    @property
    def bgbr(self)->int4: ...

    @property
    def bgbg(self)->int4: ...

    @property
    def bgbb(self)->int4: ...

    @property
    def bgba(self)->int4: ...

    @property
    def bgar(self)->int4: ...

    @bgar.setter
    def bgar(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bgag(self)->int4: ...

    @property
    def bgab(self)->int4: ...

    @property
    def bgaa(self)->int4: ...

    @property
    def bbrr(self)->int4: ...

    @property
    def bbrg(self)->int4: ...

    @property
    def bbrb(self)->int4: ...

    @property
    def bbra(self)->int4: ...

    @property
    def bbgr(self)->int4: ...

    @property
    def bbgg(self)->int4: ...

    @property
    def bbgb(self)->int4: ...

    @property
    def bbga(self)->int4: ...

    @property
    def bbbr(self)->int4: ...

    @property
    def bbbg(self)->int4: ...

    @property
    def bbbb(self)->int4: ...

    @property
    def bbba(self)->int4: ...

    @property
    def bbar(self)->int4: ...

    @property
    def bbag(self)->int4: ...

    @property
    def bbab(self)->int4: ...

    @property
    def bbaa(self)->int4: ...

    @property
    def barr(self)->int4: ...

    @property
    def barg(self)->int4: ...

    @barg.setter
    def barg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def barb(self)->int4: ...

    @property
    def bara(self)->int4: ...

    @property
    def bagr(self)->int4: ...

    @bagr.setter
    def bagr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def bagg(self)->int4: ...

    @property
    def bagb(self)->int4: ...

    @property
    def baga(self)->int4: ...

    @property
    def babr(self)->int4: ...

    @property
    def babg(self)->int4: ...

    @property
    def babb(self)->int4: ...

    @property
    def baba(self)->int4: ...

    @property
    def baar(self)->int4: ...

    @property
    def baag(self)->int4: ...

    @property
    def baab(self)->int4: ...

    @property
    def baaa(self)->int4: ...

    @property
    def arrr(self)->int4: ...

    @property
    def arrg(self)->int4: ...

    @property
    def arrb(self)->int4: ...

    @property
    def arra(self)->int4: ...

    @property
    def argr(self)->int4: ...

    @property
    def argg(self)->int4: ...

    @property
    def argb(self)->int4: ...

    @argb.setter
    def argb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def arga(self)->int4: ...

    @property
    def arbr(self)->int4: ...

    @property
    def arbg(self)->int4: ...

    @arbg.setter
    def arbg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def arbb(self)->int4: ...

    @property
    def arba(self)->int4: ...

    @property
    def arar(self)->int4: ...

    @property
    def arag(self)->int4: ...

    @property
    def arab(self)->int4: ...

    @property
    def araa(self)->int4: ...

    @property
    def agrr(self)->int4: ...

    @property
    def agrg(self)->int4: ...

    @property
    def agrb(self)->int4: ...

    @agrb.setter
    def agrb(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def agra(self)->int4: ...

    @property
    def aggr(self)->int4: ...

    @property
    def aggg(self)->int4: ...

    @property
    def aggb(self)->int4: ...

    @property
    def agga(self)->int4: ...

    @property
    def agbr(self)->int4: ...

    @agbr.setter
    def agbr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def agbg(self)->int4: ...

    @property
    def agbb(self)->int4: ...

    @property
    def agba(self)->int4: ...

    @property
    def agar(self)->int4: ...

    @property
    def agag(self)->int4: ...

    @property
    def agab(self)->int4: ...

    @property
    def agaa(self)->int4: ...

    @property
    def abrr(self)->int4: ...

    @property
    def abrg(self)->int4: ...

    @abrg.setter
    def abrg(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def abrb(self)->int4: ...

    @property
    def abra(self)->int4: ...

    @property
    def abgr(self)->int4: ...

    @abgr.setter
    def abgr(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def abgg(self)->int4: ...

    @property
    def abgb(self)->int4: ...

    @property
    def abga(self)->int4: ...

    @property
    def abbr(self)->int4: ...

    @property
    def abbg(self)->int4: ...

    @property
    def abbb(self)->int4: ...

    @property
    def abba(self)->int4: ...

    @property
    def abar(self)->int4: ...

    @property
    def abag(self)->int4: ...

    @property
    def abab(self)->int4: ...

    @property
    def abaa(self)->int4: ...

    @property
    def aarr(self)->int4: ...

    @property
    def aarg(self)->int4: ...

    @property
    def aarb(self)->int4: ...

    @property
    def aara(self)->int4: ...

    @property
    def aagr(self)->int4: ...

    @property
    def aagg(self)->int4: ...

    @property
    def aagb(self)->int4: ...

    @property
    def aaga(self)->int4: ...

    @property
    def aabr(self)->int4: ...

    @property
    def aabg(self)->int4: ...

    @property
    def aabb(self)->int4: ...

    @property
    def aaba(self)->int4: ...

    @property
    def aaar(self)->int4: ...

    @property
    def aaag(self)->int4: ...

    @property
    def aaab(self)->int4: ...

    @property
    def aaaa(self)->int4: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s2(self)->int: ...

    @s2.setter
    def s2(self, value:Union[bool, int, float])->None: ...

    @property
    def s3(self)->int: ...

    @s3.setter
    def s3(self, value:Union[bool, int, float])->None: ...

    @property
    def s00(self)->int2: ...

    @property
    def s01(self)->int2: ...

    @s01.setter
    def s01(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s02(self)->int2: ...

    @s02.setter
    def s02(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s03(self)->int2: ...

    @s03.setter
    def s03(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s10(self)->int2: ...

    @s10.setter
    def s10(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s11(self)->int2: ...

    @property
    def s12(self)->int2: ...

    @s12.setter
    def s12(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s13(self)->int2: ...

    @s13.setter
    def s13(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s20(self)->int2: ...

    @s20.setter
    def s20(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s21(self)->int2: ...

    @s21.setter
    def s21(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s22(self)->int2: ...

    @property
    def s23(self)->int2: ...

    @s23.setter
    def s23(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s30(self)->int2: ...

    @s30.setter
    def s30(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s31(self)->int2: ...

    @s31.setter
    def s31(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s32(self)->int2: ...

    @s32.setter
    def s32(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s33(self)->int2: ...

    @property
    def s000(self)->int3: ...

    @property
    def s001(self)->int3: ...

    @property
    def s002(self)->int3: ...

    @property
    def s003(self)->int3: ...

    @property
    def s010(self)->int3: ...

    @property
    def s011(self)->int3: ...

    @property
    def s012(self)->int3: ...

    @s012.setter
    def s012(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s013(self)->int3: ...

    @s013.setter
    def s013(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s020(self)->int3: ...

    @property
    def s021(self)->int3: ...

    @s021.setter
    def s021(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s022(self)->int3: ...

    @property
    def s023(self)->int3: ...

    @s023.setter
    def s023(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s030(self)->int3: ...

    @property
    def s031(self)->int3: ...

    @s031.setter
    def s031(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s032(self)->int3: ...

    @s032.setter
    def s032(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s033(self)->int3: ...

    @property
    def s100(self)->int3: ...

    @property
    def s101(self)->int3: ...

    @property
    def s102(self)->int3: ...

    @s102.setter
    def s102(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s103(self)->int3: ...

    @s103.setter
    def s103(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s110(self)->int3: ...

    @property
    def s111(self)->int3: ...

    @property
    def s112(self)->int3: ...

    @property
    def s113(self)->int3: ...

    @property
    def s120(self)->int3: ...

    @s120.setter
    def s120(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s121(self)->int3: ...

    @property
    def s122(self)->int3: ...

    @property
    def s123(self)->int3: ...

    @s123.setter
    def s123(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s130(self)->int3: ...

    @s130.setter
    def s130(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s131(self)->int3: ...

    @property
    def s132(self)->int3: ...

    @s132.setter
    def s132(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s133(self)->int3: ...

    @property
    def s200(self)->int3: ...

    @property
    def s201(self)->int3: ...

    @s201.setter
    def s201(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s202(self)->int3: ...

    @property
    def s203(self)->int3: ...

    @s203.setter
    def s203(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s210(self)->int3: ...

    @s210.setter
    def s210(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s211(self)->int3: ...

    @property
    def s212(self)->int3: ...

    @property
    def s213(self)->int3: ...

    @s213.setter
    def s213(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s220(self)->int3: ...

    @property
    def s221(self)->int3: ...

    @property
    def s222(self)->int3: ...

    @property
    def s223(self)->int3: ...

    @property
    def s230(self)->int3: ...

    @s230.setter
    def s230(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s231(self)->int3: ...

    @s231.setter
    def s231(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s232(self)->int3: ...

    @property
    def s233(self)->int3: ...

    @property
    def s300(self)->int3: ...

    @property
    def s301(self)->int3: ...

    @s301.setter
    def s301(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s302(self)->int3: ...

    @s302.setter
    def s302(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s303(self)->int3: ...

    @property
    def s310(self)->int3: ...

    @s310.setter
    def s310(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s311(self)->int3: ...

    @property
    def s312(self)->int3: ...

    @s312.setter
    def s312(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s313(self)->int3: ...

    @property
    def s320(self)->int3: ...

    @s320.setter
    def s320(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s321(self)->int3: ...

    @s321.setter
    def s321(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s322(self)->int3: ...

    @property
    def s323(self)->int3: ...

    @property
    def s330(self)->int3: ...

    @property
    def s331(self)->int3: ...

    @property
    def s332(self)->int3: ...

    @property
    def s333(self)->int3: ...

    @property
    def s0000(self)->int4: ...

    @property
    def s0001(self)->int4: ...

    @property
    def s0002(self)->int4: ...

    @property
    def s0003(self)->int4: ...

    @property
    def s0010(self)->int4: ...

    @property
    def s0011(self)->int4: ...

    @property
    def s0012(self)->int4: ...

    @property
    def s0013(self)->int4: ...

    @property
    def s0020(self)->int4: ...

    @property
    def s0021(self)->int4: ...

    @property
    def s0022(self)->int4: ...

    @property
    def s0023(self)->int4: ...

    @property
    def s0030(self)->int4: ...

    @property
    def s0031(self)->int4: ...

    @property
    def s0032(self)->int4: ...

    @property
    def s0033(self)->int4: ...

    @property
    def s0100(self)->int4: ...

    @property
    def s0101(self)->int4: ...

    @property
    def s0102(self)->int4: ...

    @property
    def s0103(self)->int4: ...

    @property
    def s0110(self)->int4: ...

    @property
    def s0111(self)->int4: ...

    @property
    def s0112(self)->int4: ...

    @property
    def s0113(self)->int4: ...

    @property
    def s0120(self)->int4: ...

    @property
    def s0121(self)->int4: ...

    @property
    def s0122(self)->int4: ...

    @property
    def s0123(self)->int4: ...

    @s0123.setter
    def s0123(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0130(self)->int4: ...

    @property
    def s0131(self)->int4: ...

    @property
    def s0132(self)->int4: ...

    @s0132.setter
    def s0132(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0133(self)->int4: ...

    @property
    def s0200(self)->int4: ...

    @property
    def s0201(self)->int4: ...

    @property
    def s0202(self)->int4: ...

    @property
    def s0203(self)->int4: ...

    @property
    def s0210(self)->int4: ...

    @property
    def s0211(self)->int4: ...

    @property
    def s0212(self)->int4: ...

    @property
    def s0213(self)->int4: ...

    @s0213.setter
    def s0213(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0220(self)->int4: ...

    @property
    def s0221(self)->int4: ...

    @property
    def s0222(self)->int4: ...

    @property
    def s0223(self)->int4: ...

    @property
    def s0230(self)->int4: ...

    @property
    def s0231(self)->int4: ...

    @s0231.setter
    def s0231(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0232(self)->int4: ...

    @property
    def s0233(self)->int4: ...

    @property
    def s0300(self)->int4: ...

    @property
    def s0301(self)->int4: ...

    @property
    def s0302(self)->int4: ...

    @property
    def s0303(self)->int4: ...

    @property
    def s0310(self)->int4: ...

    @property
    def s0311(self)->int4: ...

    @property
    def s0312(self)->int4: ...

    @s0312.setter
    def s0312(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0313(self)->int4: ...

    @property
    def s0320(self)->int4: ...

    @property
    def s0321(self)->int4: ...

    @s0321.setter
    def s0321(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s0322(self)->int4: ...

    @property
    def s0323(self)->int4: ...

    @property
    def s0330(self)->int4: ...

    @property
    def s0331(self)->int4: ...

    @property
    def s0332(self)->int4: ...

    @property
    def s0333(self)->int4: ...

    @property
    def s1000(self)->int4: ...

    @property
    def s1001(self)->int4: ...

    @property
    def s1002(self)->int4: ...

    @property
    def s1003(self)->int4: ...

    @property
    def s1010(self)->int4: ...

    @property
    def s1011(self)->int4: ...

    @property
    def s1012(self)->int4: ...

    @property
    def s1013(self)->int4: ...

    @property
    def s1020(self)->int4: ...

    @property
    def s1021(self)->int4: ...

    @property
    def s1022(self)->int4: ...

    @property
    def s1023(self)->int4: ...

    @s1023.setter
    def s1023(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1030(self)->int4: ...

    @property
    def s1031(self)->int4: ...

    @property
    def s1032(self)->int4: ...

    @s1032.setter
    def s1032(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1033(self)->int4: ...

    @property
    def s1100(self)->int4: ...

    @property
    def s1101(self)->int4: ...

    @property
    def s1102(self)->int4: ...

    @property
    def s1103(self)->int4: ...

    @property
    def s1110(self)->int4: ...

    @property
    def s1111(self)->int4: ...

    @property
    def s1112(self)->int4: ...

    @property
    def s1113(self)->int4: ...

    @property
    def s1120(self)->int4: ...

    @property
    def s1121(self)->int4: ...

    @property
    def s1122(self)->int4: ...

    @property
    def s1123(self)->int4: ...

    @property
    def s1130(self)->int4: ...

    @property
    def s1131(self)->int4: ...

    @property
    def s1132(self)->int4: ...

    @property
    def s1133(self)->int4: ...

    @property
    def s1200(self)->int4: ...

    @property
    def s1201(self)->int4: ...

    @property
    def s1202(self)->int4: ...

    @property
    def s1203(self)->int4: ...

    @s1203.setter
    def s1203(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1210(self)->int4: ...

    @property
    def s1211(self)->int4: ...

    @property
    def s1212(self)->int4: ...

    @property
    def s1213(self)->int4: ...

    @property
    def s1220(self)->int4: ...

    @property
    def s1221(self)->int4: ...

    @property
    def s1222(self)->int4: ...

    @property
    def s1223(self)->int4: ...

    @property
    def s1230(self)->int4: ...

    @s1230.setter
    def s1230(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1231(self)->int4: ...

    @property
    def s1232(self)->int4: ...

    @property
    def s1233(self)->int4: ...

    @property
    def s1300(self)->int4: ...

    @property
    def s1301(self)->int4: ...

    @property
    def s1302(self)->int4: ...

    @s1302.setter
    def s1302(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1303(self)->int4: ...

    @property
    def s1310(self)->int4: ...

    @property
    def s1311(self)->int4: ...

    @property
    def s1312(self)->int4: ...

    @property
    def s1313(self)->int4: ...

    @property
    def s1320(self)->int4: ...

    @s1320.setter
    def s1320(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s1321(self)->int4: ...

    @property
    def s1322(self)->int4: ...

    @property
    def s1323(self)->int4: ...

    @property
    def s1330(self)->int4: ...

    @property
    def s1331(self)->int4: ...

    @property
    def s1332(self)->int4: ...

    @property
    def s1333(self)->int4: ...

    @property
    def s2000(self)->int4: ...

    @property
    def s2001(self)->int4: ...

    @property
    def s2002(self)->int4: ...

    @property
    def s2003(self)->int4: ...

    @property
    def s2010(self)->int4: ...

    @property
    def s2011(self)->int4: ...

    @property
    def s2012(self)->int4: ...

    @property
    def s2013(self)->int4: ...

    @s2013.setter
    def s2013(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2020(self)->int4: ...

    @property
    def s2021(self)->int4: ...

    @property
    def s2022(self)->int4: ...

    @property
    def s2023(self)->int4: ...

    @property
    def s2030(self)->int4: ...

    @property
    def s2031(self)->int4: ...

    @s2031.setter
    def s2031(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2032(self)->int4: ...

    @property
    def s2033(self)->int4: ...

    @property
    def s2100(self)->int4: ...

    @property
    def s2101(self)->int4: ...

    @property
    def s2102(self)->int4: ...

    @property
    def s2103(self)->int4: ...

    @s2103.setter
    def s2103(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2110(self)->int4: ...

    @property
    def s2111(self)->int4: ...

    @property
    def s2112(self)->int4: ...

    @property
    def s2113(self)->int4: ...

    @property
    def s2120(self)->int4: ...

    @property
    def s2121(self)->int4: ...

    @property
    def s2122(self)->int4: ...

    @property
    def s2123(self)->int4: ...

    @property
    def s2130(self)->int4: ...

    @s2130.setter
    def s2130(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2131(self)->int4: ...

    @property
    def s2132(self)->int4: ...

    @property
    def s2133(self)->int4: ...

    @property
    def s2200(self)->int4: ...

    @property
    def s2201(self)->int4: ...

    @property
    def s2202(self)->int4: ...

    @property
    def s2203(self)->int4: ...

    @property
    def s2210(self)->int4: ...

    @property
    def s2211(self)->int4: ...

    @property
    def s2212(self)->int4: ...

    @property
    def s2213(self)->int4: ...

    @property
    def s2220(self)->int4: ...

    @property
    def s2221(self)->int4: ...

    @property
    def s2222(self)->int4: ...

    @property
    def s2223(self)->int4: ...

    @property
    def s2230(self)->int4: ...

    @property
    def s2231(self)->int4: ...

    @property
    def s2232(self)->int4: ...

    @property
    def s2233(self)->int4: ...

    @property
    def s2300(self)->int4: ...

    @property
    def s2301(self)->int4: ...

    @s2301.setter
    def s2301(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2302(self)->int4: ...

    @property
    def s2303(self)->int4: ...

    @property
    def s2310(self)->int4: ...

    @s2310.setter
    def s2310(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s2311(self)->int4: ...

    @property
    def s2312(self)->int4: ...

    @property
    def s2313(self)->int4: ...

    @property
    def s2320(self)->int4: ...

    @property
    def s2321(self)->int4: ...

    @property
    def s2322(self)->int4: ...

    @property
    def s2323(self)->int4: ...

    @property
    def s2330(self)->int4: ...

    @property
    def s2331(self)->int4: ...

    @property
    def s2332(self)->int4: ...

    @property
    def s2333(self)->int4: ...

    @property
    def s3000(self)->int4: ...

    @property
    def s3001(self)->int4: ...

    @property
    def s3002(self)->int4: ...

    @property
    def s3003(self)->int4: ...

    @property
    def s3010(self)->int4: ...

    @property
    def s3011(self)->int4: ...

    @property
    def s3012(self)->int4: ...

    @s3012.setter
    def s3012(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3013(self)->int4: ...

    @property
    def s3020(self)->int4: ...

    @property
    def s3021(self)->int4: ...

    @s3021.setter
    def s3021(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3022(self)->int4: ...

    @property
    def s3023(self)->int4: ...

    @property
    def s3030(self)->int4: ...

    @property
    def s3031(self)->int4: ...

    @property
    def s3032(self)->int4: ...

    @property
    def s3033(self)->int4: ...

    @property
    def s3100(self)->int4: ...

    @property
    def s3101(self)->int4: ...

    @property
    def s3102(self)->int4: ...

    @s3102.setter
    def s3102(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3103(self)->int4: ...

    @property
    def s3110(self)->int4: ...

    @property
    def s3111(self)->int4: ...

    @property
    def s3112(self)->int4: ...

    @property
    def s3113(self)->int4: ...

    @property
    def s3120(self)->int4: ...

    @s3120.setter
    def s3120(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3121(self)->int4: ...

    @property
    def s3122(self)->int4: ...

    @property
    def s3123(self)->int4: ...

    @property
    def s3130(self)->int4: ...

    @property
    def s3131(self)->int4: ...

    @property
    def s3132(self)->int4: ...

    @property
    def s3133(self)->int4: ...

    @property
    def s3200(self)->int4: ...

    @property
    def s3201(self)->int4: ...

    @s3201.setter
    def s3201(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3202(self)->int4: ...

    @property
    def s3203(self)->int4: ...

    @property
    def s3210(self)->int4: ...

    @s3210.setter
    def s3210(self, value:Union[bool, int, float, genVec4])->None: ...

    @property
    def s3211(self)->int4: ...

    @property
    def s3212(self)->int4: ...

    @property
    def s3213(self)->int4: ...

    @property
    def s3220(self)->int4: ...

    @property
    def s3221(self)->int4: ...

    @property
    def s3222(self)->int4: ...

    @property
    def s3223(self)->int4: ...

    @property
    def s3230(self)->int4: ...

    @property
    def s3231(self)->int4: ...

    @property
    def s3232(self)->int4: ...

    @property
    def s3233(self)->int4: ...

    @property
    def s3300(self)->int4: ...

    @property
    def s3301(self)->int4: ...

    @property
    def s3302(self)->int4: ...

    @property
    def s3303(self)->int4: ...

    @property
    def s3310(self)->int4: ...

    @property
    def s3311(self)->int4: ...

    @property
    def s3312(self)->int4: ...

    @property
    def s3313(self)->int4: ...

    @property
    def s3320(self)->int4: ...

    @property
    def s3321(self)->int4: ...

    @property
    def s3322(self)->int4: ...

    @property
    def s3323(self)->int4: ...

    @property
    def s3330(self)->int4: ...

    @property
    def s3331(self)->int4: ...

    @property
    def s3332(self)->int4: ...

    @property
    def s3333(self)->int4: ...
