from typing import Union

from ..genVec2 import genVec2
from .long3 import long3
from .long4 import long4


class long2(genVec2):

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->long2: ...

    @property
    def xy(self)->long2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->long2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->long2: ...

    @property
    def xxx(self)->long3: ...

    @property
    def xxy(self)->long3: ...

    @property
    def xyx(self)->long3: ...

    @property
    def xyy(self)->long3: ...

    @property
    def yxx(self)->long3: ...

    @property
    def yxy(self)->long3: ...

    @property
    def yyx(self)->long3: ...

    @property
    def yyy(self)->long3: ...

    @property
    def xxxx(self)->long4: ...

    @property
    def xxxy(self)->long4: ...

    @property
    def xxyx(self)->long4: ...

    @property
    def xxyy(self)->long4: ...

    @property
    def xyxx(self)->long4: ...

    @property
    def xyxy(self)->long4: ...

    @property
    def xyyx(self)->long4: ...

    @property
    def xyyy(self)->long4: ...

    @property
    def yxxx(self)->long4: ...

    @property
    def yxxy(self)->long4: ...

    @property
    def yxyx(self)->long4: ...

    @property
    def yxyy(self)->long4: ...

    @property
    def yyxx(self)->long4: ...

    @property
    def yyxy(self)->long4: ...

    @property
    def yyyx(self)->long4: ...

    @property
    def yyyy(self)->long4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->long2: ...

    @property
    def rg(self)->long2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->long2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->long2: ...

    @property
    def rrr(self)->long3: ...

    @property
    def rrg(self)->long3: ...

    @property
    def rgr(self)->long3: ...

    @property
    def rgg(self)->long3: ...

    @property
    def grr(self)->long3: ...

    @property
    def grg(self)->long3: ...

    @property
    def ggr(self)->long3: ...

    @property
    def ggg(self)->long3: ...

    @property
    def rrrr(self)->long4: ...

    @property
    def rrrg(self)->long4: ...

    @property
    def rrgr(self)->long4: ...

    @property
    def rrgg(self)->long4: ...

    @property
    def rgrr(self)->long4: ...

    @property
    def rgrg(self)->long4: ...

    @property
    def rggr(self)->long4: ...

    @property
    def rggg(self)->long4: ...

    @property
    def grrr(self)->long4: ...

    @property
    def grrg(self)->long4: ...

    @property
    def grgr(self)->long4: ...

    @property
    def grgg(self)->long4: ...

    @property
    def ggrr(self)->long4: ...

    @property
    def ggrg(self)->long4: ...

    @property
    def gggr(self)->long4: ...

    @property
    def gggg(self)->long4: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s00(self)->long2: ...

    @property
    def s01(self)->long2: ...

    @s01.setter
    def s01(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s10(self)->long2: ...

    @s10.setter
    def s10(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s11(self)->long2: ...

    @property
    def s000(self)->long3: ...

    @property
    def s001(self)->long3: ...

    @property
    def s010(self)->long3: ...

    @property
    def s011(self)->long3: ...

    @property
    def s100(self)->long3: ...

    @property
    def s101(self)->long3: ...

    @property
    def s110(self)->long3: ...

    @property
    def s111(self)->long3: ...

    @property
    def s0000(self)->long4: ...

    @property
    def s0001(self)->long4: ...

    @property
    def s0010(self)->long4: ...

    @property
    def s0011(self)->long4: ...

    @property
    def s0100(self)->long4: ...

    @property
    def s0101(self)->long4: ...

    @property
    def s0110(self)->long4: ...

    @property
    def s0111(self)->long4: ...

    @property
    def s1000(self)->long4: ...

    @property
    def s1001(self)->long4: ...

    @property
    def s1010(self)->long4: ...

    @property
    def s1011(self)->long4: ...

    @property
    def s1100(self)->long4: ...

    @property
    def s1101(self)->long4: ...

    @property
    def s1110(self)->long4: ...

    @property
    def s1111(self)->long4: ...
