from typing import Union

from ..genVec2 import genVec2
from .short3 import short3
from .short4 import short4


class short2(genVec2):

    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->short2: ...

    @property
    def xy(self)->short2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->short2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->short2: ...

    @property
    def xxx(self)->short3: ...

    @property
    def xxy(self)->short3: ...

    @property
    def xyx(self)->short3: ...

    @property
    def xyy(self)->short3: ...

    @property
    def yxx(self)->short3: ...

    @property
    def yxy(self)->short3: ...

    @property
    def yyx(self)->short3: ...

    @property
    def yyy(self)->short3: ...

    @property
    def xxxx(self)->short4: ...

    @property
    def xxxy(self)->short4: ...

    @property
    def xxyx(self)->short4: ...

    @property
    def xxyy(self)->short4: ...

    @property
    def xyxx(self)->short4: ...

    @property
    def xyxy(self)->short4: ...

    @property
    def xyyx(self)->short4: ...

    @property
    def xyyy(self)->short4: ...

    @property
    def yxxx(self)->short4: ...

    @property
    def yxxy(self)->short4: ...

    @property
    def yxyx(self)->short4: ...

    @property
    def yxyy(self)->short4: ...

    @property
    def yyxx(self)->short4: ...

    @property
    def yyxy(self)->short4: ...

    @property
    def yyyx(self)->short4: ...

    @property
    def yyyy(self)->short4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->short2: ...

    @property
    def rg(self)->short2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->short2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->short2: ...

    @property
    def rrr(self)->short3: ...

    @property
    def rrg(self)->short3: ...

    @property
    def rgr(self)->short3: ...

    @property
    def rgg(self)->short3: ...

    @property
    def grr(self)->short3: ...

    @property
    def grg(self)->short3: ...

    @property
    def ggr(self)->short3: ...

    @property
    def ggg(self)->short3: ...

    @property
    def rrrr(self)->short4: ...

    @property
    def rrrg(self)->short4: ...

    @property
    def rrgr(self)->short4: ...

    @property
    def rrgg(self)->short4: ...

    @property
    def rgrr(self)->short4: ...

    @property
    def rgrg(self)->short4: ...

    @property
    def rggr(self)->short4: ...

    @property
    def rggg(self)->short4: ...

    @property
    def grrr(self)->short4: ...

    @property
    def grrg(self)->short4: ...

    @property
    def grgr(self)->short4: ...

    @property
    def grgg(self)->short4: ...

    @property
    def ggrr(self)->short4: ...

    @property
    def ggrg(self)->short4: ...

    @property
    def gggr(self)->short4: ...

    @property
    def gggg(self)->short4: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s00(self)->short2: ...

    @property
    def s01(self)->short2: ...

    @s01.setter
    def s01(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s10(self)->short2: ...

    @s10.setter
    def s10(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s11(self)->short2: ...

    @property
    def s000(self)->short3: ...

    @property
    def s001(self)->short3: ...

    @property
    def s010(self)->short3: ...

    @property
    def s011(self)->short3: ...

    @property
    def s100(self)->short3: ...

    @property
    def s101(self)->short3: ...

    @property
    def s110(self)->short3: ...

    @property
    def s111(self)->short3: ...

    @property
    def s0000(self)->short4: ...

    @property
    def s0001(self)->short4: ...

    @property
    def s0010(self)->short4: ...

    @property
    def s0011(self)->short4: ...

    @property
    def s0100(self)->short4: ...

    @property
    def s0101(self)->short4: ...

    @property
    def s0110(self)->short4: ...

    @property
    def s0111(self)->short4: ...

    @property
    def s1000(self)->short4: ...

    @property
    def s1001(self)->short4: ...

    @property
    def s1010(self)->short4: ...

    @property
    def s1011(self)->short4: ...

    @property
    def s1100(self)->short4: ...

    @property
    def s1101(self)->short4: ...

    @property
    def s1110(self)->short4: ...

    @property
    def s1111(self)->short4: ...
