from typing import Union

from .genVec8 import genVec8


class char8(genVec8):

    def __len__(self)->int: ...

    def __repr__(self)->str: ...

    def __str__(self)->str: ...
    
    @property
    def x(self)->str: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->str: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->str: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def w(self)->str: ...

    @w.setter
    def w(self, value:Union[bool, int, float])->None: ...

    @property
    def r(self)->str: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->str: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def sb(self)->str: ...

    @sb.setter
    def sb(self, value:Union[bool, int, float])->None: ...

    @property
    def sa(self)->str: ...

    @sa.setter
    def sa(self, value:Union[bool, int, float])->None: ...

    @property
    def s0(self)->str: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->str: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s2(self)->str: ...

    @s2.setter
    def s2(self, value:Union[bool, int, float])->None: ...

    @property
    def s3(self)->str: ...

    @s3.setter
    def s3(self, value:Union[bool, int, float])->None: ...

    @property
    def s4(self)->str: ...

    @s4.setter
    def s4(self, value:Union[bool, int, float])->None: ...

    @property
    def s5(self)->str: ...

    @s5.setter
    def s5(self, value:Union[bool, int, float])->None: ...

    @property
    def s6(self)->str: ...

    @s6.setter
    def s6(self, value:Union[bool, int, float])->None: ...

    @property
    def s7(self)->str: ...

    @s7.setter
    def s7(self, value:Union[bool, int, float])->None: ...
