from typing import Union

from .genVec16 import genVec16


class short16(genVec16):

    def __len__(self)->int: ...

    def __repr__(self)->str: ...

    def __str__(self)->str: ...
    
    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->int: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def w(self)->int: ...

    @w.setter
    def w(self, value:Union[bool, int, float])->None: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def sb(self)->int: ...

    @sb.setter
    def sb(self, value:Union[bool, int, float])->None: ...

    @property
    def sa(self)->int: ...

    @sa.setter
    def sa(self, value:Union[bool, int, float])->None: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s2(self)->int: ...

    @s2.setter
    def s2(self, value:Union[bool, int, float])->None: ...

    @property
    def s3(self)->int: ...

    @s3.setter
    def s3(self, value:Union[bool, int, float])->None: ...

    @property
    def s4(self)->int: ...

    @s4.setter
    def s4(self, value:Union[bool, int, float])->None: ...

    @property
    def s5(self)->int: ...

    @s5.setter
    def s5(self, value:Union[bool, int, float])->None: ...

    @property
    def s6(self)->int: ...

    @s6.setter
    def s6(self, value:Union[bool, int, float])->None: ...

    @property
    def s7(self)->int: ...

    @s7.setter
    def s7(self, value:Union[bool, int, float])->None: ...

    @property
    def s8(self)->int: ...

    @s8.setter
    def s8(self, value:Union[bool, int, float])->None: ...

    @property
    def s9(self)->int: ...

    @s9.setter
    def s9(self, value:Union[bool, int, float])->None: ...

    @property
    def sA(self)->int: ...

    @sA.setter
    def sA(self, value:Union[bool, int, float])->None: ...

    @property
    def sB(self)->int: ...

    @sB.setter
    def sB(self, value:Union[bool, int, float])->None: ...

    @property
    def sC(self)->int: ...

    @sC.setter
    def sC(self, value:Union[bool, int, float])->None: ...

    @property
    def sD(self)->int: ...

    @sD.setter
    def sD(self, value:Union[bool, int, float])->None: ...

    @property
    def sE(self)->int: ...

    @sE.setter
    def sE(self, value:Union[bool, int, float])->None: ...

    @property
    def sF(self)->int: ...

    @sF.setter
    def sF(self, value:Union[bool, int, float])->None: ...

    @property
    def sa(self)->int: ...

    @sa.setter
    def sa(self, value:Union[bool, int, float])->None: ...

    @property
    def sb(self)->int: ...

    @sb.setter
    def sb(self, value:Union[bool, int, float])->None: ...

    @property
    def sc(self)->int: ...

    @sc.setter
    def sc(self, value:Union[bool, int, float])->None: ...

    @property
    def sd(self)->int: ...

    @sd.setter
    def sd(self, value:Union[bool, int, float])->None: ...

    @property
    def se(self)->int: ...

    @se.setter
    def se(self, value:Union[bool, int, float])->None: ...

    @property
    def sf(self)->int: ...

    @sf.setter
    def sf(self, value:Union[bool, int, float])->None: ...
