from typing import Union

from .genVec2 import genVec2
from .ulong3 import ulong3
from .ulong4 import ulong4


class ulong2(genVec2):

    def __len__(self)->int: ...

    def __repr__(self)->str: ...

    def __str__(self)->str: ...
    
    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->ulong2: ...

    @property
    def xy(self)->ulong2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->ulong2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->ulong2: ...

    @property
    def xxx(self)->ulong3: ...

    @property
    def xxy(self)->ulong3: ...

    @property
    def xyx(self)->ulong3: ...

    @property
    def xyy(self)->ulong3: ...

    @property
    def yxx(self)->ulong3: ...

    @property
    def yxy(self)->ulong3: ...

    @property
    def yyx(self)->ulong3: ...

    @property
    def yyy(self)->ulong3: ...

    @property
    def xxxx(self)->ulong4: ...

    @property
    def xxxy(self)->ulong4: ...

    @property
    def xxyx(self)->ulong4: ...

    @property
    def xxyy(self)->ulong4: ...

    @property
    def xyxx(self)->ulong4: ...

    @property
    def xyxy(self)->ulong4: ...

    @property
    def xyyx(self)->ulong4: ...

    @property
    def xyyy(self)->ulong4: ...

    @property
    def yxxx(self)->ulong4: ...

    @property
    def yxxy(self)->ulong4: ...

    @property
    def yxyx(self)->ulong4: ...

    @property
    def yxyy(self)->ulong4: ...

    @property
    def yyxx(self)->ulong4: ...

    @property
    def yyxy(self)->ulong4: ...

    @property
    def yyyx(self)->ulong4: ...

    @property
    def yyyy(self)->ulong4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->ulong2: ...

    @property
    def rg(self)->ulong2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->ulong2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->ulong2: ...

    @property
    def rrr(self)->ulong3: ...

    @property
    def rrg(self)->ulong3: ...

    @property
    def rgr(self)->ulong3: ...

    @property
    def rgg(self)->ulong3: ...

    @property
    def grr(self)->ulong3: ...

    @property
    def grg(self)->ulong3: ...

    @property
    def ggr(self)->ulong3: ...

    @property
    def ggg(self)->ulong3: ...

    @property
    def rrrr(self)->ulong4: ...

    @property
    def rrrg(self)->ulong4: ...

    @property
    def rrgr(self)->ulong4: ...

    @property
    def rrgg(self)->ulong4: ...

    @property
    def rgrr(self)->ulong4: ...

    @property
    def rgrg(self)->ulong4: ...

    @property
    def rggr(self)->ulong4: ...

    @property
    def rggg(self)->ulong4: ...

    @property
    def grrr(self)->ulong4: ...

    @property
    def grrg(self)->ulong4: ...

    @property
    def grgr(self)->ulong4: ...

    @property
    def grgg(self)->ulong4: ...

    @property
    def ggrr(self)->ulong4: ...

    @property
    def ggrg(self)->ulong4: ...

    @property
    def gggr(self)->ulong4: ...

    @property
    def gggg(self)->ulong4: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s00(self)->ulong2: ...

    @property
    def s01(self)->ulong2: ...

    @s01.setter
    def s01(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s10(self)->ulong2: ...

    @s10.setter
    def s10(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s11(self)->ulong2: ...

    @property
    def s000(self)->ulong3: ...

    @property
    def s001(self)->ulong3: ...

    @property
    def s010(self)->ulong3: ...

    @property
    def s011(self)->ulong3: ...

    @property
    def s100(self)->ulong3: ...

    @property
    def s101(self)->ulong3: ...

    @property
    def s110(self)->ulong3: ...

    @property
    def s111(self)->ulong3: ...

    @property
    def s0000(self)->ulong4: ...

    @property
    def s0001(self)->ulong4: ...

    @property
    def s0010(self)->ulong4: ...

    @property
    def s0011(self)->ulong4: ...

    @property
    def s0100(self)->ulong4: ...

    @property
    def s0101(self)->ulong4: ...

    @property
    def s0110(self)->ulong4: ...

    @property
    def s0111(self)->ulong4: ...

    @property
    def s1000(self)->ulong4: ...

    @property
    def s1001(self)->ulong4: ...

    @property
    def s1010(self)->ulong4: ...

    @property
    def s1011(self)->ulong4: ...

    @property
    def s1100(self)->ulong4: ...

    @property
    def s1101(self)->ulong4: ...

    @property
    def s1110(self)->ulong4: ...

    @property
    def s1111(self)->ulong4: ...
