from typing import Union

from ....vec_types import genVec3, genVec2
from .long2 import long2
from .long4 import long4


class long3(genVec3):

    def __len__(self)->int: ...

    def __repr__(self)->str: ...

    def __str__(self)->str: ...
    
    @property
    def x(self)->int: ...

    @x.setter
    def x(self, value:Union[bool, int, float])->None: ...

    @property
    def y(self)->int: ...

    @y.setter
    def y(self, value:Union[bool, int, float])->None: ...

    @property
    def z(self)->int: ...

    @z.setter
    def z(self, value:Union[bool, int, float])->None: ...

    @property
    def xx(self)->long2: ...

    @property
    def xy(self)->long2: ...

    @xy.setter
    def xy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def xz(self)->long2: ...

    @xz.setter
    def xz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yx(self)->long2: ...

    @yx.setter
    def yx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def yy(self)->long2: ...

    @property
    def yz(self)->long2: ...

    @yz.setter
    def yz(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zx(self)->long2: ...

    @zx.setter
    def zx(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zy(self)->long2: ...

    @zy.setter
    def zy(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def zz(self)->long2: ...

    @property
    def xxx(self)->long3: ...

    @property
    def xxy(self)->long3: ...

    @property
    def xxz(self)->long3: ...

    @property
    def xyx(self)->long3: ...

    @property
    def xyy(self)->long3: ...

    @property
    def xyz(self)->long3: ...

    @xyz.setter
    def xyz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzx(self)->long3: ...

    @property
    def xzy(self)->long3: ...

    @xzy.setter
    def xzy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def xzz(self)->long3: ...

    @property
    def yxx(self)->long3: ...

    @property
    def yxy(self)->long3: ...

    @property
    def yxz(self)->long3: ...

    @yxz.setter
    def yxz(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yyx(self)->long3: ...

    @property
    def yyy(self)->long3: ...

    @property
    def yyz(self)->long3: ...

    @property
    def yzx(self)->long3: ...

    @yzx.setter
    def yzx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def yzy(self)->long3: ...

    @property
    def yzz(self)->long3: ...

    @property
    def zxx(self)->long3: ...

    @property
    def zxy(self)->long3: ...

    @zxy.setter
    def zxy(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zxz(self)->long3: ...

    @property
    def zyx(self)->long3: ...

    @zyx.setter
    def zyx(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def zyy(self)->long3: ...

    @property
    def zyz(self)->long3: ...

    @property
    def zzx(self)->long3: ...

    @property
    def zzy(self)->long3: ...

    @property
    def zzz(self)->long3: ...

    @property
    def xxxx(self)->long4: ...

    @property
    def xxxy(self)->long4: ...

    @property
    def xxxz(self)->long4: ...

    @property
    def xxyx(self)->long4: ...

    @property
    def xxyy(self)->long4: ...

    @property
    def xxyz(self)->long4: ...

    @property
    def xxzx(self)->long4: ...

    @property
    def xxzy(self)->long4: ...

    @property
    def xxzz(self)->long4: ...

    @property
    def xyxx(self)->long4: ...

    @property
    def xyxy(self)->long4: ...

    @property
    def xyxz(self)->long4: ...

    @property
    def xyyx(self)->long4: ...

    @property
    def xyyy(self)->long4: ...

    @property
    def xyyz(self)->long4: ...

    @property
    def xyzx(self)->long4: ...

    @property
    def xyzy(self)->long4: ...

    @property
    def xyzz(self)->long4: ...

    @property
    def xzxx(self)->long4: ...

    @property
    def xzxy(self)->long4: ...

    @property
    def xzxz(self)->long4: ...

    @property
    def xzyx(self)->long4: ...

    @property
    def xzyy(self)->long4: ...

    @property
    def xzyz(self)->long4: ...

    @property
    def xzzx(self)->long4: ...

    @property
    def xzzy(self)->long4: ...

    @property
    def xzzz(self)->long4: ...

    @property
    def yxxx(self)->long4: ...

    @property
    def yxxy(self)->long4: ...

    @property
    def yxxz(self)->long4: ...

    @property
    def yxyx(self)->long4: ...

    @property
    def yxyy(self)->long4: ...

    @property
    def yxyz(self)->long4: ...

    @property
    def yxzx(self)->long4: ...

    @property
    def yxzy(self)->long4: ...

    @property
    def yxzz(self)->long4: ...

    @property
    def yyxx(self)->long4: ...

    @property
    def yyxy(self)->long4: ...

    @property
    def yyxz(self)->long4: ...

    @property
    def yyyx(self)->long4: ...

    @property
    def yyyy(self)->long4: ...

    @property
    def yyyz(self)->long4: ...

    @property
    def yyzx(self)->long4: ...

    @property
    def yyzy(self)->long4: ...

    @property
    def yyzz(self)->long4: ...

    @property
    def yzxx(self)->long4: ...

    @property
    def yzxy(self)->long4: ...

    @property
    def yzxz(self)->long4: ...

    @property
    def yzyx(self)->long4: ...

    @property
    def yzyy(self)->long4: ...

    @property
    def yzyz(self)->long4: ...

    @property
    def yzzx(self)->long4: ...

    @property
    def yzzy(self)->long4: ...

    @property
    def yzzz(self)->long4: ...

    @property
    def zxxx(self)->long4: ...

    @property
    def zxxy(self)->long4: ...

    @property
    def zxxz(self)->long4: ...

    @property
    def zxyx(self)->long4: ...

    @property
    def zxyy(self)->long4: ...

    @property
    def zxyz(self)->long4: ...

    @property
    def zxzx(self)->long4: ...

    @property
    def zxzy(self)->long4: ...

    @property
    def zxzz(self)->long4: ...

    @property
    def zyxx(self)->long4: ...

    @property
    def zyxy(self)->long4: ...

    @property
    def zyxz(self)->long4: ...

    @property
    def zyyx(self)->long4: ...

    @property
    def zyyy(self)->long4: ...

    @property
    def zyyz(self)->long4: ...

    @property
    def zyzx(self)->long4: ...

    @property
    def zyzy(self)->long4: ...

    @property
    def zyzz(self)->long4: ...

    @property
    def zzxx(self)->long4: ...

    @property
    def zzxy(self)->long4: ...

    @property
    def zzxz(self)->long4: ...

    @property
    def zzyx(self)->long4: ...

    @property
    def zzyy(self)->long4: ...

    @property
    def zzyz(self)->long4: ...

    @property
    def zzzx(self)->long4: ...

    @property
    def zzzy(self)->long4: ...

    @property
    def zzzz(self)->long4: ...

    @property
    def r(self)->int: ...

    @r.setter
    def r(self, value:Union[bool, int, float])->None: ...

    @property
    def g(self)->int: ...

    @g.setter
    def g(self, value:Union[bool, int, float])->None: ...

    @property
    def b(self)->int: ...

    @b.setter
    def b(self, value:Union[bool, int, float])->None: ...

    @property
    def rr(self)->long2: ...

    @property
    def rg(self)->long2: ...

    @rg.setter
    def rg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def rb(self)->long2: ...

    @rb.setter
    def rb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gr(self)->long2: ...

    @gr.setter
    def gr(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def gg(self)->long2: ...

    @property
    def gb(self)->long2: ...

    @gb.setter
    def gb(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def br(self)->long2: ...

    @br.setter
    def br(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bg(self)->long2: ...

    @bg.setter
    def bg(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def bb(self)->long2: ...

    @property
    def rrr(self)->long3: ...

    @property
    def rrg(self)->long3: ...

    @property
    def rrb(self)->long3: ...

    @property
    def rgr(self)->long3: ...

    @property
    def rgg(self)->long3: ...

    @property
    def rgb(self)->long3: ...

    @rgb.setter
    def rgb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbr(self)->long3: ...

    @property
    def rbg(self)->long3: ...

    @rbg.setter
    def rbg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def rbb(self)->long3: ...

    @property
    def grr(self)->long3: ...

    @property
    def grg(self)->long3: ...

    @property
    def grb(self)->long3: ...

    @grb.setter
    def grb(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def ggr(self)->long3: ...

    @property
    def ggg(self)->long3: ...

    @property
    def ggb(self)->long3: ...

    @property
    def gbr(self)->long3: ...

    @gbr.setter
    def gbr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def gbg(self)->long3: ...

    @property
    def gbb(self)->long3: ...

    @property
    def brr(self)->long3: ...

    @property
    def brg(self)->long3: ...

    @brg.setter
    def brg(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def brb(self)->long3: ...

    @property
    def bgr(self)->long3: ...

    @bgr.setter
    def bgr(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def bgg(self)->long3: ...

    @property
    def bgb(self)->long3: ...

    @property
    def bbr(self)->long3: ...

    @property
    def bbg(self)->long3: ...

    @property
    def bbb(self)->long3: ...

    @property
    def rrrr(self)->long4: ...

    @property
    def rrrg(self)->long4: ...

    @property
    def rrrb(self)->long4: ...

    @property
    def rrgr(self)->long4: ...

    @property
    def rrgg(self)->long4: ...

    @property
    def rrgb(self)->long4: ...

    @property
    def rrbr(self)->long4: ...

    @property
    def rrbg(self)->long4: ...

    @property
    def rrbb(self)->long4: ...

    @property
    def rgrr(self)->long4: ...

    @property
    def rgrg(self)->long4: ...

    @property
    def rgrb(self)->long4: ...

    @property
    def rggr(self)->long4: ...

    @property
    def rggg(self)->long4: ...

    @property
    def rggb(self)->long4: ...

    @property
    def rgbr(self)->long4: ...

    @property
    def rgbg(self)->long4: ...

    @property
    def rgbb(self)->long4: ...

    @property
    def rbrr(self)->long4: ...

    @property
    def rbrg(self)->long4: ...

    @property
    def rbrb(self)->long4: ...

    @property
    def rbgr(self)->long4: ...

    @property
    def rbgg(self)->long4: ...

    @property
    def rbgb(self)->long4: ...

    @property
    def rbbr(self)->long4: ...

    @property
    def rbbg(self)->long4: ...

    @property
    def rbbb(self)->long4: ...

    @property
    def grrr(self)->long4: ...

    @property
    def grrg(self)->long4: ...

    @property
    def grrb(self)->long4: ...

    @property
    def grgr(self)->long4: ...

    @property
    def grgg(self)->long4: ...

    @property
    def grgb(self)->long4: ...

    @property
    def grbr(self)->long4: ...

    @property
    def grbg(self)->long4: ...

    @property
    def grbb(self)->long4: ...

    @property
    def ggrr(self)->long4: ...

    @property
    def ggrg(self)->long4: ...

    @property
    def ggrb(self)->long4: ...

    @property
    def gggr(self)->long4: ...

    @property
    def gggg(self)->long4: ...

    @property
    def gggb(self)->long4: ...

    @property
    def ggbr(self)->long4: ...

    @property
    def ggbg(self)->long4: ...

    @property
    def ggbb(self)->long4: ...

    @property
    def gbrr(self)->long4: ...

    @property
    def gbrg(self)->long4: ...

    @property
    def gbrb(self)->long4: ...

    @property
    def gbgr(self)->long4: ...

    @property
    def gbgg(self)->long4: ...

    @property
    def gbgb(self)->long4: ...

    @property
    def gbbr(self)->long4: ...

    @property
    def gbbg(self)->long4: ...

    @property
    def gbbb(self)->long4: ...

    @property
    def brrr(self)->long4: ...

    @property
    def brrg(self)->long4: ...

    @property
    def brrb(self)->long4: ...

    @property
    def brgr(self)->long4: ...

    @property
    def brgg(self)->long4: ...

    @property
    def brgb(self)->long4: ...

    @property
    def brbr(self)->long4: ...

    @property
    def brbg(self)->long4: ...

    @property
    def brbb(self)->long4: ...

    @property
    def bgrr(self)->long4: ...

    @property
    def bgrg(self)->long4: ...

    @property
    def bgrb(self)->long4: ...

    @property
    def bggr(self)->long4: ...

    @property
    def bggg(self)->long4: ...

    @property
    def bggb(self)->long4: ...

    @property
    def bgbr(self)->long4: ...

    @property
    def bgbg(self)->long4: ...

    @property
    def bgbb(self)->long4: ...

    @property
    def bbrr(self)->long4: ...

    @property
    def bbrg(self)->long4: ...

    @property
    def bbrb(self)->long4: ...

    @property
    def bbgr(self)->long4: ...

    @property
    def bbgg(self)->long4: ...

    @property
    def bbgb(self)->long4: ...

    @property
    def bbbr(self)->long4: ...

    @property
    def bbbg(self)->long4: ...

    @property
    def bbbb(self)->long4: ...

    @property
    def s0(self)->int: ...

    @s0.setter
    def s0(self, value:Union[bool, int, float])->None: ...

    @property
    def s1(self)->int: ...

    @s1.setter
    def s1(self, value:Union[bool, int, float])->None: ...

    @property
    def s2(self)->int: ...

    @s2.setter
    def s2(self, value:Union[bool, int, float])->None: ...

    @property
    def s00(self)->long2: ...

    @property
    def s01(self)->long2: ...

    @s01.setter
    def s01(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s02(self)->long2: ...

    @s02.setter
    def s02(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s10(self)->long2: ...

    @s10.setter
    def s10(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s11(self)->long2: ...

    @property
    def s12(self)->long2: ...

    @s12.setter
    def s12(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s20(self)->long2: ...

    @s20.setter
    def s20(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s21(self)->long2: ...

    @s21.setter
    def s21(self, value:Union[bool, int, float, genVec2])->None: ...

    @property
    def s22(self)->long2: ...

    @property
    def s000(self)->long3: ...

    @property
    def s001(self)->long3: ...

    @property
    def s002(self)->long3: ...

    @property
    def s010(self)->long3: ...

    @property
    def s011(self)->long3: ...

    @property
    def s012(self)->long3: ...

    @s012.setter
    def s012(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s020(self)->long3: ...

    @property
    def s021(self)->long3: ...

    @s021.setter
    def s021(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s022(self)->long3: ...

    @property
    def s100(self)->long3: ...

    @property
    def s101(self)->long3: ...

    @property
    def s102(self)->long3: ...

    @s102.setter
    def s102(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s110(self)->long3: ...

    @property
    def s111(self)->long3: ...

    @property
    def s112(self)->long3: ...

    @property
    def s120(self)->long3: ...

    @s120.setter
    def s120(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s121(self)->long3: ...

    @property
    def s122(self)->long3: ...

    @property
    def s200(self)->long3: ...

    @property
    def s201(self)->long3: ...

    @s201.setter
    def s201(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s202(self)->long3: ...

    @property
    def s210(self)->long3: ...

    @s210.setter
    def s210(self, value:Union[bool, int, float, genVec3])->None: ...

    @property
    def s211(self)->long3: ...

    @property
    def s212(self)->long3: ...

    @property
    def s220(self)->long3: ...

    @property
    def s221(self)->long3: ...

    @property
    def s222(self)->long3: ...

    @property
    def s0000(self)->long4: ...

    @property
    def s0001(self)->long4: ...

    @property
    def s0002(self)->long4: ...

    @property
    def s0010(self)->long4: ...

    @property
    def s0011(self)->long4: ...

    @property
    def s0012(self)->long4: ...

    @property
    def s0020(self)->long4: ...

    @property
    def s0021(self)->long4: ...

    @property
    def s0022(self)->long4: ...

    @property
    def s0100(self)->long4: ...

    @property
    def s0101(self)->long4: ...

    @property
    def s0102(self)->long4: ...

    @property
    def s0110(self)->long4: ...

    @property
    def s0111(self)->long4: ...

    @property
    def s0112(self)->long4: ...

    @property
    def s0120(self)->long4: ...

    @property
    def s0121(self)->long4: ...

    @property
    def s0122(self)->long4: ...

    @property
    def s0200(self)->long4: ...

    @property
    def s0201(self)->long4: ...

    @property
    def s0202(self)->long4: ...

    @property
    def s0210(self)->long4: ...

    @property
    def s0211(self)->long4: ...

    @property
    def s0212(self)->long4: ...

    @property
    def s0220(self)->long4: ...

    @property
    def s0221(self)->long4: ...

    @property
    def s0222(self)->long4: ...

    @property
    def s1000(self)->long4: ...

    @property
    def s1001(self)->long4: ...

    @property
    def s1002(self)->long4: ...

    @property
    def s1010(self)->long4: ...

    @property
    def s1011(self)->long4: ...

    @property
    def s1012(self)->long4: ...

    @property
    def s1020(self)->long4: ...

    @property
    def s1021(self)->long4: ...

    @property
    def s1022(self)->long4: ...

    @property
    def s1100(self)->long4: ...

    @property
    def s1101(self)->long4: ...

    @property
    def s1102(self)->long4: ...

    @property
    def s1110(self)->long4: ...

    @property
    def s1111(self)->long4: ...

    @property
    def s1112(self)->long4: ...

    @property
    def s1120(self)->long4: ...

    @property
    def s1121(self)->long4: ...

    @property
    def s1122(self)->long4: ...

    @property
    def s1200(self)->long4: ...

    @property
    def s1201(self)->long4: ...

    @property
    def s1202(self)->long4: ...

    @property
    def s1210(self)->long4: ...

    @property
    def s1211(self)->long4: ...

    @property
    def s1212(self)->long4: ...

    @property
    def s1220(self)->long4: ...

    @property
    def s1221(self)->long4: ...

    @property
    def s1222(self)->long4: ...

    @property
    def s2000(self)->long4: ...

    @property
    def s2001(self)->long4: ...

    @property
    def s2002(self)->long4: ...

    @property
    def s2010(self)->long4: ...

    @property
    def s2011(self)->long4: ...

    @property
    def s2012(self)->long4: ...

    @property
    def s2020(self)->long4: ...

    @property
    def s2021(self)->long4: ...

    @property
    def s2022(self)->long4: ...

    @property
    def s2100(self)->long4: ...

    @property
    def s2101(self)->long4: ...

    @property
    def s2102(self)->long4: ...

    @property
    def s2110(self)->long4: ...

    @property
    def s2111(self)->long4: ...

    @property
    def s2112(self)->long4: ...

    @property
    def s2120(self)->long4: ...

    @property
    def s2121(self)->long4: ...

    @property
    def s2122(self)->long4: ...

    @property
    def s2200(self)->long4: ...

    @property
    def s2201(self)->long4: ...

    @property
    def s2202(self)->long4: ...

    @property
    def s2210(self)->long4: ...

    @property
    def s2211(self)->long4: ...

    @property
    def s2212(self)->long4: ...

    @property
    def s2220(self)->long4: ...

    @property
    def s2221(self)->long4: ...

    @property
    def s2222(self)->long4: ...
